// Generated by tools/re/generate_ce_contracts.py; do not edit.
// Offline identity evidence is not title admission or headset acceptance.
#pragma once
#include <cstdint>
#include <array>
namespace halo_ce::contract {
struct Entry { const char* name; uint32_t rva; const char* pattern; bool unwind; };
struct Witness { uint32_t rva; const char* pattern; };
struct Relative { uint32_t rva, size, displacement, target; };
struct Pointer { uint32_t rva, target; };
inline constexpr uint32_t imageSize=0x3D82000;
inline constexpr uint32_t timestamp=0x68A0E4CF;
inline constexpr std::array<Entry,32> entries={{
    {"native_player_window",0xbbca64,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8D A8 48 FB FF FF 48 81 EC 90 05 00 00",true},
    {"native_frustum",0xb8f690,"48 8B C4 55 53 56 57 41 54 41 56 41 57 48 8D 68 A1 48 81 EC F0 00 00 00 44 0F BF 51 32",true},
    {"native_camera_build",0xac450c,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 55 48 8D 68 A1 48 81 EC 90 00 00 00 48 8B FA 48 8B D9 48 85 D2 0F 84 46 01 00 00 F2",true},
    {"native_window_loop",0xbbce28,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 48 89 78 20 41 56 48 83 EC 30 F3 0F 10 44 24 68 41 BE 01 00 00 00",true},
    {"native_game_render",0xac47c0,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 20 57 41 54 41 55 41 56 41 57 48 83 EC 60",true},
    {"initialized_clock_render_gate",0xac269c,"40 53 48 83 EC 30 48 8B 05 BF D6 3D 02 ?? ?? ?? ??",true},
    {"anniversary_camera_view_rebuild",0x11aba0,"48 8B C4 48 89 58 10 48 89 70 18 55 57 41 56 48 8D 68 A1 48 81 EC 00 01 00 00 0F 29 70 D8 0F 29 78 C8 44 0F 29 40 B8 44 0F 29 48 A8",true},
    {"anniversary_camera_projection_rebuild",0x11ae90,"40 53 48 83 EC 50 F3 0F 10 81 4C 01 00 00 48 8B D9 F3 0F 59 05 73 49 83 01",true},
    {"anniversary_camera_culling_rebuild",0x11e5f0,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 48 8D A8 38 FF FF FF 48 81 EC C0 01 00 00",true},
    {"anniversary_view_append",0x2ea720,"48 8B C4 48 89 58 18 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 78 FC FF FF",true},
    {"anniversary_primary_view_pair_builder",0x4547e0,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 57 41 54 41 55 41 56 41 57 48 81 EC D0 00 00 00 8B 0D 93 33 6C 02",true},
    {"anniversary_view_prepare",0x455170,"4C 8B DC 53 56 41 56 48 81 EC 90 00 00 00 48 8B 05 8B FE 71 01 48 33 C4",true},
    {"anniversary_per_view_output",0x45e2b0,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 60 80 3D 4E CE 71 01 00 8B D9",true},
    {"anniversary_full_frame_not_replayable",0x455a10,"48 8B C4 55 41 54 41 55 41 56 41 57 48 8D A8 88 F3 FF FF 48 81 EC 50 0D 00 00",true},
    {"anniversary_backend_constructor",0x203580,"48 89 4C 24 08 56 57 41 56 48 83 EC 40 48 C7 44 24 30 FE FF FF FF 48 89 5C 24 68 48 89 6C 24 70 41 0F B6 F1 49 8B E8 48",true},
    {"anniversary_surface_transfer",0x204c40,"40 55 56 57 41 54 41 55 41 56 41 57 48 81 EC 90 00 00 00 48 C7 44 24 50 FE FF FF FF 48 89 9C 24 E0 00 00 00 48 8B 05 A5",true},
    {"anniversary_surface_selector",0xad5f0,"4C 8B 91 A8 00 00 00 4C 8B C1 4D 85 D2 74 45 48 8B 05 B2 D0 B3 01 44 8B",false},
    {"anniversary_legacy_mode_reader",0x84730,"48 8B C4 48 89 48 08 57 48 83 EC 40 48 C7 40 E0 FE FF FF FF 48 89 58 10 49 8B D9 48 8B F9 C7 40 DC 00 00 00 00 83 3D 28",true},
    {"anniversary_preparation_complete_not_wait",0x4556b0,"48 89 5C 24 08 57 48 83 EC 20 4C 8D 41 70 48 8B F9 E8 9A B9 E8 FF 45 33 C0 48 8D 57 70",true},
    {"anniversary_job_execute",0xc2560,"40 55 41 54 41 55 41 56 41 57 48 83 EC 30 48 8D 6C 24 20 48 89 5D 40 48 89 75 48 48 89 7D 50 48 8B 05 8A 2A AB 01",true},
    {"anniversary_job_pump_until_target",0xc2d50,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 3D 12 12 B7 01 48 8B F2 0F 1F 80 00 00 00 00",true},
    {"anniversary_texture_create",0x229b70,"40 55 56 57 41 54 41 55 41 56 41 57 48 81 EC 90 00 00 00 48 8D 6C 24 20 48 89 9D C0 00 00 00 48 8B 05 7A B4 94 01",true},
    {"anniversary_texture_import_2d",0x22a1e0,"4C 8B DC 57 41 56 48 81 EC 88 00 00 00 48 8B 05 1C AE 94 01 48 33 C4 48 89 44 24 70 48 8B 02 48 8B F9",true},
    {"anniversary_texture_release_resources",0x22b0a0,"48 89 5C 24 18 55 48 83 EC 20 33 ED 48 89 74 24 30 48 8B D9 48 89 7C 24 38 8B F5 39 A9 F0 00 00 00",true},
    {"anniversary_view_list_reset",0x2eacd0,"40 53 56 48 81 EC 78 04 00 00 48 8B 05 2F A3 88 01 48 33 C4 48 89 84 24 00 04 00 00 48 8B F1 48 89 AC 24 98 04 00 00",true},
    {"anniversary_camera_upload",0x2eb9f0,"48 89 5C 24 08 55 56 57 48 81 EC E0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 D0 00 00 00 48 8B 3D ?? ?? ?? ?? 49 8B F0 F3 41 0F 10 88 3C 01 00 00",true},
    {"anniversary_depth_mesh_pass",0x4577b0,"40 53 48 83 EC 70 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 44 24 60 48 8B 0D ?? ?? ?? ?? 49 63 D9",true},
    {"anniversary_scene_camera_update",0x5434b0,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 49 8B F9 49 8B F0 8B EA 48 8B D9 4D 85 C0",true},
    {"anniversary_scene_camera_regions",0x543550,"44 89 4C 24 20 4C 89 44 24 18 89 54 24 10 53 56 41 55 41 57 48 83 EC 58 8B 81 10 01 00 00 45 8B E9",true},
    {"anniversary_scene_refresh_consumer",0x543cb0,"40 57 48 83 EC 40 48 C7 44 24 20 FE FF FF FF 48 89 5C 24 50 48 89 6C 24 58 48 89 74 24 60 48 8B EA 48 8B D9 48 8D B1 B8 01 00 00",true},
    {"anniversary_scene_static_visibility_rebuild",0x543af0,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 44 8B 82 50 28 00 00 33 FF 48 8B EA",true},
    {"anniversary_scene_region_visibility_apply",0x542f00,"40 53 48 83 EC 50 48 8B D9 8B 89 A8 01 00 00 8B C1 C1 E8 0B A8 01 0F 85 A9 01 00 00 F6 C1 60 0F 84 A0 01 00 00",true},
}};
inline constexpr std::array<Witness,138> witnesses={{
    {0xbbccad,"E8 ?? ?? ?? ??"},
    {0xbbcee6,"E8 ?? ?? ?? ??"},
    {0xac483f,"48 8D 15 ?? ?? ?? ??"},
    {0xac48e0,"E8 ?? ?? ?? ??"},
    {0xac4942,"E8 ?? ?? ?? ??"},
    {0xac4956,"E8 ?? ?? ?? ??"},
    {0xac26a2,"48 8B 05 ?? ?? ?? ??"},
    {0xac2704,"E8 ?? ?? ?? ??"},
    {0x2eab31,"48 69 C9 C8 03 00 00"},
    {0x2eab9d,"44 89 6C 39 1C"},
    {0x2eabb2,"48 8D 4A 40"},
    {0x2eab09,"89 87 20 BD 00 00"},
    {0x2eab12,"F2 0F 11 84 8F 24 BD 00 00"},
    {0x2eab22,"48 63 4F 08"},
    {0x2eab29,"89 47 08"},
    {0x4aa9e4,"41 3B 77 08"},
    {0x2ea9dc,"48 63 8F 20 BD 00 00"},
    {0x2eaa02,"48 63 8F 20 BD 00 00"},
    {0x2eab04,"F2 0F 10 45 90"},
    {0x2eab50,"88 44 39 2E"},
    {0x2ea8b3,"E8 ?? ?? ?? ??"},
    {0x2ea96d,"E8 ?? ?? ?? ??"},
    {0x4aa97c,"E8 ?? ?? ?? ??"},
    {0x4aa983,"E8 ?? ?? ?? ??"},
    {0x4aa9a4,"E8 ?? ?? ?? ??"},
    {0x4ab8c6,"E8 ?? ?? ?? ??"},
    {0x4abc88,"E8 ?? ?? ?? ??"},
    {0x4ae0df,"E8 ?? ?? ?? ??"},
    {0x4af40f,"E8 ?? ?? ?? ??"},
    {0x4afa58,"E8 ?? ?? ?? ??"},
    {0x454a95,"45 84 E4"},
    {0x454aa7,"83 0E 01"},
    {0x454aaa,"41 B8 0B 02 00 00"},
    {0x454ab0,"83 B8 38 02 00 00 00"},
    {0x454a7b,"89 86 C0 00 00 00"},
    {0x454a8d,"F3 0F 11 B6 C4 00 00 00"},
    {0x454b52,"89 86 88 04 00 00"},
    {0x454b5d,"F3 0F 11 B6 8C 04 00 00"},
    {0x454c93,"E8 88 5A E9 FF"},
    {0x454a69,"E8 ?? ?? ?? ??"},
    {0x454c93,"E8 ?? ?? ?? ??"},
    {0x4547ff,"8B 0D 93 33 6C 02"},
    {0x454812,"48 8B 1D 77 33 6C 02"},
    {0x4549f0,"83 3D A1 31 6C 02 00"},
    {0x4549f9,"48 8B 05 90 31 6C 02"},
    {0x454a86,"48 8B 05 4B 73 9E 02"},
    {0x454ab7,"48 8B 0D D2 30 6C 02"},
    {0x454ac4,"44 8B 0D CD 30 6C 02"},
    {0x454c1e,"8B 05 74 2F 6C 02"},
    {0x45518d,"83 B9 58 BE 00 00 00"},
    {0x455273,"49 8D 56 70"},
    {0x455277,"48 81 C1 B0 00 00 00"},
    {0x45527e,"41 B8 E8 BD 00 00"},
    {0x45560d,"49 8D 56 70"},
    {0x455308,"E8 ?? ?? ?? ??"},
    {0x455611,"E8 ?? ?? ?? ??"},
    {0x455373,"E8 ?? ?? ?? ??"},
    {0x455506,"E8 ?? ?? ?? ??"},
    {0x45526c,"48 8B 0D ?? ?? ?? ??"},
    {0x455284,"E8 ?? ?? ?? ??"},
    {0x455267,"E8 ?? ?? ?? ??"},
    {0x4551b7,"48 8B 05 22 58 79 01"},
    {0x4552fa,"48 8B 15 DF 56 79 01"},
    {0x45530d,"48 8B 15 CC 56 79 01"},
    {0x455341,"4C 8B 05 98 56 79 01"},
    {0x455362,"48 8B 15 77 56 79 01"},
    {0x455493,"4C 8B 0D 46 55 79 01"},
    {0x45555b,"48 8B 05 7E 54 79 01"},
    {0x45557e,"44 88 05 8F 5B 72 01"},
    {0x45e2de,"BA 01 00 00 04"},
    {0x45e34c,"89 74 24 44"},
    {0x45e35d,"89 44 24 44"},
    {0x45e370,"FF 90 90 01 00 00"},
    {0x45e434,"C7 05 DE CC 71 01 FF FF FF FF"},
    {0x45e2ce,"E8 ?? ?? ?? ??"},
    {0x456f18,"B8 FF FF FF FF"},
    {0x456f1d,"F0 0F C1 05 3F FC 75 01"},
    {0x456dd0,"E8 ?? ?? ?? ??"},
    {0x203643,"48 8D 05 C6 66 5F 01"},
    {0x20364a,"48 89 03"},
    {0x203660,"48 89 AB E0 0C 00 00"},
    {0x204c7c,"4C 8B 22"},
    {0x204c7f,"4C 8B 6A 08"},
    {0x204d2b,"48 8B A8 70 01 00 00"},
    {0x204d4b,"4C 8B 98 E0 00 00 00"},
    {0x204d94,"48 8B 90 E0 00 00 00"},
    {0x204c92,"FF 15 98 C5 54 01"},
    {0x204d9e,"FF D5"},
    {0x204e0a,"FF 15 48 C4 54 01"},
    {0x204d46,"E8 ?? ?? ?? ??"},
    {0x204d69,"E8 ?? ?? ?? ??"},
    {0x204db6,"E8 ?? ?? ?? ??"},
    {0x204dc5,"E8 ?? ?? ?? ??"},
    {0xad5f0,"4C 8B 91 A8 00 00 00"},
    {0xad61e,"48 8B 8A 18 01 00 00"},
    {0xad63c,"49 8B 80 B0 00 00 00"},
    {0x4556d9,"C7 87 60 BE 00 00 01 00 00 00"},
    {0x4556ed,"48 FF 25 C4 BB 2F 01"},
    {0x4556c1,"E8 ?? ?? ?? ??"},
    {0x4556cd,"E8 ?? ?? ?? ??"},
    {0xc2599,"FF 50 08"},
    {0xc259c,"4C 8D 63 10"},
    {0xc25a3,"FF 15 87 EC 68 01"},
    {0xc2656,"FF 15 5C EC 68 01"},
    {0xc2d86,"E8 D5 F7 FF FF"},
    {0xc2d8b,"48 3B DE"},
    {0xc2d8e,"74 26"},
    {0xc2dae,"FF 15 0C E5 68 01"},
    {0x229fc8,"48 C7 45 4C 01 00 00 00"},
    {0x229fe2,"41 8B 87 D0 00 00 00"},
    {0x22a01e,"4D 8D 8F E0 00 00 00"},
    {0x22a036,"FF 50 28"},
    {0x2eba33,"4C 89 87 98 BE 00 00"},
    {0x4562ba,"E8 ?? ?? ?? ??"},
    {0x456a81,"E8 ?? ?? ?? ??"},
    {0x457c02,"E8 ?? ?? ?? ??"},
    {0x4575d5,"48 8B 88 18 03 00 00"},
    {0x22b84e,"48 8B 80 08 01 00 00"},
    {0x456324,"E8 87 14 00 00"},
    {0x5434ca,"8B EA"},
    {0x543526,"85 ED 74 0A 81 8B 10 01 00 00 00 01 00 00"},
    {0x454e60,"0F B6 93 92 00 00 00 FF 90 30 02 00 00"},
    {0x454e7b,"C6 83 92 00 00 00 00"},
    {0x454e8a,"48 FF A0 38 02 00 00"},
    {0x4557ff,"C6 80 92 00 00 00 01"},
    {0x415418,"C6 80 92 00 00 00 01"},
    {0x543521,"E8 ?? ?? ?? ??"},
    {0x543568,"8B 81 10 01 00 00"},
    {0x543579,"0F BA F0 0C 89 81 10 01 00 00"},
    {0x543589,"4D 85 C0 74 0F 4D 85 D2 74 0A 0F BA E8 0C 89 81 10 01 00 00"},
    {0x543d30,"83 BB 28 01 00 00 00 74 59 8B C1 C1 E8 08 A8 01 75 06 0F BA F1 0B EB 09"},
    {0x543d61,"85 FF 74 2D 81 A3 10 01 00 00 FF FE FF FF"},
    {0x543d75,"E8 ?? ?? ?? ??"},
    {0x543b49,"F7 41 2C 00 00 02 00 75 1C 0F B6 81 8E 00 00 00 39 79 1C 7E 06 24 F9 0C 01 EB 04 24 FE 0C 06 88 81 8E 00 00 00"},
    {0x543c60,"39 BE 28 01 00 00 7E 26 48 8B DF 0F 1F 44 00 00 48 8B 8E 20 01 00 00 48 8B 0C 0B E8 80 F2 FF FF FF C7 48 8D 5B 08 3B BE 28 01 00 00"},
    {0x543c7b,"E8 ?? ?? ?? ??"},
    {0x542f09,"8B 89 A8 01 00 00 8B C1 C1 E8 0B A8 01 0F 85 A9 01 00 00 F6 C1 60 0F 84 A0 01 00 00"},
    {0x542f2a,"8B C1 C1 E8 05 48 89 7C 24 40 83 E0 01 03 C0 4C 89 64 24 38 C1 E9 06 4C 89 6C 24 30 4C 89 7C 24 20 44 8B F8 80 E1 01 74 04 41 83 CF 04"},
}};
inline constexpr std::array<Relative,58> relatives={{
    {0xbbccad,5,1,0xbbcf30},
    {0xbbcee6,5,1,0xbbca64},
    {0xac483f,7,3,0x2e9fe80},
    {0xac48e0,5,1,0xac450c},
    {0xac4942,5,1,0xac450c},
    {0xac4956,5,1,0xbbce28},
    {0xac26a2,7,3,0x2e9fd68},
    {0xac2704,5,1,0xac47c0},
    {0x2ea8b3,5,1,0x11ae90},
    {0x2ea96d,5,1,0x11e5f0},
    {0x4aa97c,5,1,0x4ada70},
    {0x4aa983,5,1,0x4aec10},
    {0x4aa9a4,5,1,0x4ab4e0},
    {0x4ab8c6,5,1,0x2ea720},
    {0x4abc88,5,1,0x2ea720},
    {0x4ae0df,5,1,0x2ea720},
    {0x4af40f,5,1,0x2ea720},
    {0x4afa58,5,1,0x2ea720},
    {0x454a69,5,1,0x2ea720},
    {0x454c93,5,1,0x2ea720},
    {0x4547ff,6,2,0x2b17b98},
    {0x454812,7,3,0x2b17b90},
    {0x4549f0,7,2,0x2b17b98},
    {0x4549f9,7,3,0x2b17b90},
    {0x454a86,7,3,0x2e3bdd8},
    {0x454ab7,7,3,0x2b17b90},
    {0x454ac4,7,3,0x2b17b98},
    {0x454c1e,6,2,0x2b17b98},
    {0x455308,5,1,0x4547e0},
    {0x455611,5,1,0x4547e0},
    {0x455373,5,1,0x4aa740},
    {0x455506,5,1,0x4aa740},
    {0x45526c,7,3,0x1bea9e0},
    {0x455284,5,1,0x1606fb1},
    {0x455267,5,1,0x4556b0},
    {0x4551b7,7,3,0x1bea9e0},
    {0x4552fa,7,3,0x1bea9e0},
    {0x45530d,7,3,0x1bea9e0},
    {0x455341,7,3,0x1bea9e0},
    {0x455362,7,3,0x1bea9e0},
    {0x455493,7,3,0x1bea9e0},
    {0x45555b,7,3,0x1bea9e0},
    {0x45557e,7,3,0x1b7b114},
    {0x45e2ce,5,1,0x1dc2f0},
    {0x456dd0,5,1,0x45e2b0},
    {0x204d46,5,1,0xad5f0},
    {0x204d69,5,1,0xad5f0},
    {0x204db6,5,1,0xad5f0},
    {0x204dc5,5,1,0xad5f0},
    {0x4556c1,5,1,0x2e1060},
    {0x4556cd,5,1,0x4aa740},
    {0x4562ba,5,1,0x2eb9f0},
    {0x456a81,5,1,0x2eb9f0},
    {0x457c02,5,1,0x2eb9f0},
    {0x456324,5,1,0x4577b0},
    {0x543521,5,1,0x543550},
    {0x543d75,5,1,0x543af0},
    {0x543c7b,5,1,0x542f00},
}};
inline constexpr std::array<Pointer,6> pointers={{
    {0x17f9ea0,0x204c40},
    {0x17fb6e8,0x22b830},
    {0x17f9e08,0x205e40},
    {0x1819888,0x5434b0},
    {0x1819890,0x543cb0},
    {0x1819890,0x543cb0},
}};
inline constexpr uint32_t native_player_window=0xbbca64;
inline constexpr uint32_t native_frustum=0xb8f690;
inline constexpr uint32_t native_camera_build=0xac450c;
inline constexpr uint32_t native_window_loop=0xbbce28;
inline constexpr uint32_t native_game_render=0xac47c0;
inline constexpr uint32_t initialized_clock_render_gate=0xac269c;
inline constexpr uint32_t anniversary_camera_view_rebuild=0x11aba0;
inline constexpr uint32_t anniversary_camera_projection_rebuild=0x11ae90;
inline constexpr uint32_t anniversary_camera_culling_rebuild=0x11e5f0;
inline constexpr uint32_t anniversary_view_append=0x2ea720;
inline constexpr uint32_t anniversary_primary_view_pair_builder=0x4547e0;
inline constexpr uint32_t anniversary_view_prepare=0x455170;
inline constexpr uint32_t anniversary_per_view_output=0x45e2b0;
inline constexpr uint32_t anniversary_full_frame_not_replayable=0x455a10;
inline constexpr uint32_t anniversary_backend_constructor=0x203580;
inline constexpr uint32_t anniversary_surface_transfer=0x204c40;
inline constexpr uint32_t anniversary_surface_selector=0xad5f0;
inline constexpr uint32_t anniversary_legacy_mode_reader=0x84730;
inline constexpr uint32_t anniversary_preparation_complete_not_wait=0x4556b0;
inline constexpr uint32_t anniversary_job_execute=0xc2560;
inline constexpr uint32_t anniversary_job_pump_until_target=0xc2d50;
inline constexpr uint32_t anniversary_texture_create=0x229b70;
inline constexpr uint32_t anniversary_texture_import_2d=0x22a1e0;
inline constexpr uint32_t anniversary_texture_release_resources=0x22b0a0;
inline constexpr uint32_t anniversary_view_list_reset=0x2eacd0;
inline constexpr uint32_t anniversary_camera_upload=0x2eb9f0;
inline constexpr uint32_t anniversary_depth_mesh_pass=0x4577b0;
inline constexpr uint32_t anniversary_scene_camera_update=0x5434b0;
inline constexpr uint32_t anniversary_scene_camera_regions=0x543550;
inline constexpr uint32_t anniversary_scene_refresh_consumer=0x543cb0;
inline constexpr uint32_t anniversary_scene_static_visibility_rebuild=0x543af0;
inline constexpr uint32_t anniversary_scene_region_visibility_apply=0x542f00;
namespace anniversary_hud {
inline constexpr std::array<Entry,7> entries={{
    {"native_hud_callback",0x740b0,"48 8B C4 57 48 81 EC A0 00 00 00 48 C7 40 98 FE FF FF FF 48 89 58 08 48 89 70 10 0F 29 70 E8 0F 29 78 D8 33 F6 89 35 9D",true},
    {"native_hud_preamble",0x4255a0,"48 83 EC 28 48 83 3D 34 EA 80 01 00 74 3C E8 2D 6C DB FF E8 38 6D DB FF 48 8B 15 21 68 A1 02 0F 57 C0 48 8B 82 D8 00 00",true},
    {"native_target_push",0x1dc1e0,"48 8B C4 48 89 58 10 48 89 48 08 57 48 83 EC 60 48 8B 1D E9 FB C5 02 48 63 4B 10 8B 53 14 0F 10 43 18 8D 79 01 3B D7 0F",true},
    {"native_target_pop",0x1dc2f0,"40 53 48 83 EC 40 48 8B 1D E3 FA C5 02 83 7B 10 00 74 3D 48 8B 03 4C 8B 80 F8 00 00 00 8B 43 10 FF C8 48 98 48 8D 0C C0",true},
    {"native_late_hud_sequence",0x4572a5,"48 8B 05 34 37 79 01 83 B8 B8 00 00 00 00 0F 8E E9 00 00 00 F6 44 24 54 10 0F 84 DE 00 00 00 48 83 3D AC 5A 9E 02 00",false},
    {"native_hud_scissor_state",0x202d70,"48 89 5C 24 18 48 89 74 24 20 55 57 41 56 48 8D AC 24 60 FF FF FF 48 81 EC A0 01 00 00 48 8B 05 7C 22 97 01 48 33 C4 48",true},
    {"native_hud_backend_clear_state",0x203c00,"48 89 5C 24 08 57 48 83 EC 30 48 8B F9 48 8B 89 E0 0C 00 00 48 8B 01 FF 90 70 03 00 00 33 DB C7 87 C0 0F 06 00 FF FF FF FF",true},
}};
inline constexpr std::array<Witness,70> witnesses={{
    {0x740fc,"40 38 70 02"},
    {0x74361,"83 FB 01"},
    {0x743e1,"48 8B 0D F8 79 DC 02"},
    {0x8d088,"48 8D 05 21 70 FE FF"},
    {0x8d08f,"48 89 05 4A 6F BA 01"},
    {0x740db,"40 38 35 EF 7C D2 02"},
    {0x740e8,"40 38 35 11 F6 AA 02"},
    {0x740f5,"48 8B 05 34 D2 D1 02"},
    {0x74345,"E8 3E DA AB 00"},
    {0x4255c2,"48 8B 82 D8 00 00 00"},
    {0x4255c9,"C6 40 30 01"},
    {0x4255cd,"48 8B 48 08"},
    {0x4255d1,"0F 11 81 50 03 00 00"},
    {0x4255d8,"C6 82 C8 02 00 00 01"},
    {0x456d24,"8B 88 B0 00 00 00"},
    {0x4255a4,"48 83 3D 34 EA 80 01 00"},
    {0x4255ae,"E8 2D 6C DB FF"},
    {0x4255b3,"E8 38 6D DB FF"},
    {0x4255b8,"48 8B 15 21 68 A1 02"},
    {0x4255e3,"48 FF 25 F6 E9 80 01"},
    {0x456d1d,"48 8B 05 BC 3C 79 01"},
    {0x1dc1f7,"48 63 4B 10"},
    {0x1dc1fb,"8B 53 14"},
    {0x1dc1fe,"0F 10 43 18"},
    {0x1dc202,"8D 79 01"},
    {0x1dc205,"3B D7"},
    {0x1dc2b0,"48 8B 43 08"},
    {0x1dc1f0,"48 8B 1D E9 FB C5 02"},
    {0x1dc306,"4C 8B 80 F8 00 00 00"},
    {0x1dc30d,"8B 43 10"},
    {0x1dc318,"48 8B 43 08"},
    {0x1dc31c,"48 8D 14 C8"},
    {0x1dc323,"41 FF D0"},
    {0x1dc337,"89 4B 10"},
    {0x1dc2f6,"48 8B 1D E3 FA C5 02"},
    {0x4572ac,"83 B8 B8 00 00 00 00"},
    {0x4572b9,"F6 44 24 54 10"},
    {0x4572d2,"8B 80 B0 00 00 00"},
    {0x4572d8,"D1 E8"},
    {0x4572da,"A8 01"},
    {0x4572dc,"0F 85 C0 00 00 00"},
    {0x45e35d,"89 44 24 44"},
    {0x7413b,"48 0F 45 C8"},
    {0x7441d,"41 FF D2"},
    {0x456ee5,"4C 8B 80 18 03 00 00"},
    {0x4572a5,"48 8B 05 34 37 79 01"},
    {0x4572c4,"48 83 3D AC 5A 9E 02 00"},
    {0x4572f0,"E8 AB E2 FC FF"},
    {0x4572fa,"E8 51 71 00 00"},
    {0x45735a,"E8 71 9F FF FF"},
    {0x457381,"E8 DA E2 FC FF"},
    {0x4573c7,"E8 C4 70 00 00"},
    {0x45e2eb,"48 89 05 DE ED 9D 02"},
    {0x7412a,"48 8B 0D 97 8F DC 02"},
    {0x74131,"48 8B 05 98 8F DC 02"},
    {0x7413f,"48 89 0D D2 77 DC 02"},
    {0xb32106,"E8 FD 09 FE FF"},
    {0x456ece,"E8 0D 53 D8 FF"},
    {0x456eec,"48 8B 15 DD 61 9E 02"},
    {0x456efa,"E8 51 4F D8 FF"},
    {0x2034b6,"C7 85 8C 00 00 00 01 00 00 00"},
    {0x2034ea,"48 8D 55 70"},
    {0x2034f1,"FF 90 B0 00 00 00"},
    {0x205ca9,"48 8B 57 58"},
    {0x205cc7,"FF 90 58 01 00 00"},
    {0x744ac,"FF 50 28"},
    {0x203c17,"FF 90 70 03 00 00"},
    {0x2043a4,"89 9F F8 0C 00 00"},
    {0x2043aa,"48 89 9F 20 0D 00 00"},
    {0x20443e,"E9 1D 77 FD FF"},
}};
inline constexpr std::array<Relative,29> relatives={{
    {0x8d088,7,3,0x740b0},
    {0x8d08f,7,3,0x1c33fe0},
    {0x740db,7,3,0x2d9bdd1},
    {0x740e8,7,3,0x2b23700},
    {0x740f5,7,3,0x2d91330},
    {0x74345,5,1,0xb31d88},
    {0x4255a4,8,3,0x1c33fe0},
    {0x4255ae,5,1,0x1dc1e0},
    {0x4255b3,5,1,0x1dc2f0},
    {0x4255b8,7,3,0x2e3bde0},
    {0x4255e3,7,3,0x1c33fe0},
    {0x456d1d,7,3,0x1bea9e0},
    {0x1dc1f0,7,3,0x2e3bde0},
    {0x1dc2f6,7,3,0x2e3bde0},
    {0x4572a5,7,3,0x1bea9e0},
    {0x4572c4,8,3,0x2e3cd78},
    {0x4572f0,5,1,0x4255a0},
    {0x4572fa,5,1,0x45e450},
    {0x45735a,5,1,0x4512d0},
    {0x457381,5,1,0x425660},
    {0x4573c7,5,1,0x45e490},
    {0x45e2eb,7,3,0x2e3d0d0},
    {0x7412a,7,3,0x2e3d0c8},
    {0x74131,7,3,0x2e3d0d0},
    {0x7413f,7,3,0x2e3b918},
    {0xb32106,5,1,0xb12b08},
    {0x456ece,5,1,0x1dc1e0},
    {0x456eec,7,3,0x2e3d0d0},
    {0x456efa,5,1,0x1dbe50},
}};
inline constexpr std::array<Pointer,1> pointers={{
    {0x17f9d38,0x203c00},
}};
inline constexpr uint32_t native_hud_callback=0x740b0;
inline constexpr uint32_t native_hud_preamble=0x4255a0;
inline constexpr uint32_t native_target_push=0x1dc1e0;
inline constexpr uint32_t native_target_pop=0x1dc2f0;
inline constexpr uint32_t native_late_hud_sequence=0x4572a5;
inline constexpr uint32_t native_hud_scissor_state=0x202d70;
inline constexpr uint32_t native_hud_backend_clear_state=0x203c00;
}
namespace anniversary_resolution {
inline constexpr std::array<Entry,9> entries={{
    {"resolution_pool_initialize",0x2d44b0,"48 89 5C 24 20 55 56 57 41 55 41 56 48 83 EC 50 4C 8B 05 11 79 B6 02 48 8B E9 49 8B 80 18 01 00",true},
    {"resolution_pool_entry",0x20a9b0,"48 89 5C 24 10 44 89 4C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 83 EC 40 44 8B BC 24 B0 00 00",true},
    {"resolution_split_child",0x1f9d20,"48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 48 83 EC 40 8B 99 88 00 00 00 41 8B F9 45 33 C9",true},
    {"resolution_management",0x455700,"4C 8B DC 49 89 4B 08 56 57 41 54 41 56 41 57 48 81 EC 10 01 00 00 48 C7 44 24 20 FE FF FF FF 49",true},
    {"resolution_release",0x4f1ad0,"48 83 EC 28 48 8B 0D 9D B2 94 02 48 85 C9 74 05 E8 7B 40 F3 FF 48 8B 05 44 23 74 01 48 8B 48 18",true},
    {"resolution_reconfigure",0x4f11e0,"48 8B C4 55 41 54 41 55 41 56 41 57 48 8D 6C 24 90 48 81 EC 70 01 00 00 48 C7 44 24 60 FE FF FF",true},
    {"resolution_legacy_reload",0x80dd0,"40 55 41 54 41 55 41 56 41 57 48 8D AC 24 A0 E3 FF FF B8 60 1D 00 00 E8 74 60 58 01 48 2B E0 48",true},
    {"resolution_legacy_dispose",0x82170,"41 54 41 55 48 83 EC 38 4C 8B E1 45 33 ED 48 8B 0D DB 97 DB 02 48 85 C9 74 0C E8 01 7F 18 00 4C",true},
    {"resolution_legacy_hud_quad",0xb0ec20,"48 8B C4 48 89 58 18 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 80 48 81 EC 80 01 00 00 0F 29 70 B8 0F 29 78 A8 44 0F 29 40 98 48 8B 05 BE 63 06 01 48 33 C4 48 89 45 40 45 33 E4 48 89 54 24 20 44 38 25 0A E8 06 01 4C 8B FA 48 8B F9 0F 84 C0 0E 00 00 45 8D 6C 24 01 66 44 39 2D FF 18 ED",true},
}};
inline constexpr std::array<Witness,18> witnesses={{
    {0x20ac2b,"48 8B BC 24 B8 00 00 00 48 89 44 1A 10"},
    {0x20acf5,"41 FF 92 A8 00 00 00 48 63 43 0C 48 6B C8 38 44 89 7C 19 18"},
    {0x20ad4b,"48 63 4B 0C 8D 41 01 89 43 0C"},
    {0x1f42cf,"41 0F BF 76 10 41 0F BF 46 12 99 2B C2 D1 F8 8B E8"},
    {0x1f42fe,"44 8B CD 44 8B C6 49 8B CE"},
    {0x1f4369,"44 8B CD 44 8B C6 49 8B D7 49 8B CE"},
    {0x1f4307,"E8 14 5A 00 00"},
    {0x1f4375,"E8 A6 59 00 00"},
    {0x4551b2,"E8 49 05 00 00"},
    {0x80e43,"0F 84 56 08 00 00"},
    {0x80e3c,"44 39 35 19 1F E2 02"},
    {0x82196,"44 39 2D BF 0B E2 02"},
    {0x821c1,"44 89 2D 94 0B E2 02"},
    {0x822b7,"4C 8D 3D D2 9F AF 01"},
    {0x822be,"48 8D 1D 0B B1 AF 01"},
    {0xb0f2f6,"48 8D 35 D3 DE 06 01"},
    {0xb0f3cb,"4C 8D 05 1E DE 06 01"},
    {0xb0f4c2,"48 8D 35 47 DD 06 01"},
}};
inline constexpr std::array<Relative,11> relatives={{
    {0x1f4307,5,1,0x1f9d20},
    {0x1f4375,5,1,0x1f9d20},
    {0x4551b2,5,1,0x455700},
    {0x80e3c,7,3,0x2ea2d5c},
    {0x82196,7,3,0x2ea2d5c},
    {0x821c1,7,3,0x2ea2d5c},
    {0x822b7,7,3,0x1b7c290},
    {0x822be,7,3,0x1b7d3d0},
    {0xb0f2f6,7,3,0x1b7d1d0},
    {0xb0f3cb,7,3,0x1b7d1f0},
    {0xb0f4c2,7,3,0x1b7d210},
}};
inline constexpr std::array<Pointer,3> pointers={{
    {0x1815368,0x2d44b0},
    {0x17f0cf8,0x80dd0},
    {0x17f0d08,0x82170},
}};
inline constexpr uint32_t resolution_pool_initialize=0x2d44b0;
inline constexpr uint32_t resolution_pool_entry=0x20a9b0;
inline constexpr uint32_t resolution_split_child=0x1f9d20;
inline constexpr uint32_t resolution_management=0x455700;
inline constexpr uint32_t resolution_release=0x4f1ad0;
inline constexpr uint32_t resolution_reconfigure=0x4f11e0;
inline constexpr uint32_t resolution_legacy_reload=0x80dd0;
inline constexpr uint32_t resolution_legacy_dispose=0x82170;
inline constexpr uint32_t resolution_legacy_hud_quad=0xb0ec20;
inline constexpr uint32_t resolution_legacy_initialized=0x2ea2d5c;
inline constexpr uint32_t resolution_legacy_effects_begin=0x1b7c290;
inline constexpr uint32_t resolution_legacy_effects_end=0x1b7d3d0;
inline constexpr uint32_t resolution_legacy_hud_screen=0x1b7d1d0;
inline constexpr uint32_t resolution_legacy_hud_meter=0x1b7d1f0;
inline constexpr uint32_t resolution_legacy_hud_meter_background=0x1b7d210;
}
namespace audio_listener {
inline constexpr std::array<Entry,3> entries={{
    {"audio_listener_submit",0xabcc54,"48 8B C4 48 89 58 18 55 56 57 48 8D 68 D8 48 81 EC 10 01 00 00 0F 29 70 D8 0F 29 78 C8 44 0F 29 40 B8 44 0F 29 48 A8",true},
    {"audio_listener_producer",0xb4cb80,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 55 41 54 41 55 41 56 41 57 48 8D A8 B8 FD FF FF 48 81 EC 20 03 00 00",true},
    {"audio_listener_basis",0xba24ec,"48 83 EC 28 C7 01 00 00 80 3F F2 0F 10 02 F2 0F 11 41 04 8B 42 08 89 41 0C",true},
}};
inline constexpr std::array<Witness,10> witnesses={{
    {0xabcc90,"8B F9 48 8D 4A 48 48 8B F2"},
    {0xabcd5e,"F3 0F 10 46 24 F3 0F 59 05 95 2A E9 00 F3 0F 59 F1 F3 0F 10 4E 28 F3 0F 59 0D 44 31 E9 00 F3 0F 11"},
    {0xabce19,"8B D7 FF 90 A0 00 00 00"},
    {0xabcca3,"E8 ?? ?? ?? ??"},
    {0xb4cd39,"4D 8D 46 2C 49 8D 56 20"},
    {0xb4cdc1,"8B 41 30 41 0F 11 41 30 0F 10 41 20 41 0F 11 49 40 41 0F 11 41 50 41 89 41 60"},
    {0xb4ceee,"48 03 D0 41 88 36 48 8B 05 1D 74 10 01 FF 50 28"},
    {0xb4cd41,"E8 ?? ?? ?? ??"},
    {0xb4cd61,"E8 ?? ?? ?? ??"},
    {0xba2558,"F3 0F 11 49 10 F3 0F 5C DA F3 0F 11 79 18 0F 28 3C 24 F3 0F 11 59 14 F2 41 0F 10 00 F2 0F 11 41 1C 41 8B 40 08 89 41 24 33 C0 48 89 41 28 89 41 30 48 83 C4 28"},
}};
inline constexpr std::array<Relative,3> relatives={{
    {0xabcca3,5,1,0x77e70},
    {0xb4cd41,5,1,0xba24ec},
    {0xb4cd61,5,1,0xba31b0},
}};
inline constexpr std::array<Pointer,2> pointers={{
    {0x18988a8,0x1b7b880},
    {0x1b7b8a8,0xabcc54},
}};
inline constexpr uint32_t audio_listener_submit=0xabcc54;
inline constexpr uint32_t audio_listener_producer=0xb4cb80;
inline constexpr uint32_t audio_listener_basis=0xba24ec;
}
namespace camera_effect {
inline constexpr std::array<Entry,2> entries={{
    {"camera_effect_transform",0xbac0cc,"48 8B C4 48 89 58 10 55 56 57 41 54 41 55 41 56 41 57 48 8D 68 A1 48 81 EC F0 00 00 00 0F 10 1D 10 E3 CE 00",true},
    {"camera_effect_consumer",0xac450c,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 55 48 8D 68 A1 48 81 EC 90 00 00 00 48 8B FA 48 8B D9 48 85 D2 0F 84 46 01 00 00 F2",true},
}};
inline constexpr std::array<Witness,10> witnesses={{
    {0xbac1ef,"49 6B C4 34"},
    {0xbac7c4,"0F 10 07 0F 11 06 0F 10 4F 10 0F 11 4E 10 0F 10 47 20 0F 11 46 20 8B 47 30 89 46 30"},
    {0xbac7bf,"E8 ?? ?? ?? ??"},
    {0xbac7f1,"E8 ?? ?? ?? ??"},
    {0xac4611,"0F B7 0B 48 8D 55 1F"},
    {0xac461d,"4C 8D 47 2C 48 8D 57 20 48 8D 4D E7"},
    {0xac4639,"48 8D 55 1F 48 8D 4D E7"},
    {0xac4618,"E8 ?? ?? ?? ??"},
    {0xac4629,"E8 ?? ?? ?? ??"},
    {0xac4649,"E8 ?? ?? ?? ??"},
}};
inline constexpr std::array<Relative,5> relatives={{
    {0xbac7bf,5,1,0xba3360},
    {0xbac7f1,5,1,0xba807c},
    {0xac4618,5,1,0xbac0cc},
    {0xac4629,5,1,0xba24ec},
    {0xac4649,5,1,0xba3360},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t camera_effect_transform=0xbac0cc;
inline constexpr uint32_t camera_effect_consumer=0xac450c;
}
namespace classic {
inline constexpr std::array<Entry,19> entries={{
    {"classic_view_render",0xbbcf30,"40 55 53 56 57 41 54 41 56 41 57 48 8D AC 24 70 FE FF FF 48 81 EC 90 02 00 00 48 8B 05 BF 80 FB 00 48 33 C4 48 89 85 80 01 00 00 48 8B BD F0 01",true},
    {"classic_render_target_select",0xb51670,"48 89 5C 24 18 55 56 57 41 56 41 57 48 8D 6C 24 D1 48 81 EC B0 00 00 00 48 8B 05 81 39 02 01 48 33 C4 48 89 45 1F 33 FF 45 8B F8 45 8A F1 44 0F",true},
    {"classic_saber_target_route",0xaeb00,"48 89 5C 24 18 48 89 74 24 20 41 56 48 83 EC 40 48 89 6C 24 50 48 8D 35 F4 CD D8 02 48 89 7C 24 58 45 8B F0 33 FF 48 63 EA 39 3D 55 BF AC 01 48",true},
    {"classic_postprocess_ping_pong",0xb0d40,"48 8B C4 55 48 8D 68 E8 48 81 EC 10 01 00 00 48 C7 45 80 FE FF FF FF 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 0F 29 70 E8 48 8B 05 9E 42",true},
    {"classic_outer_output",0xae0df4,"40 53 48 83 EC 30 33 DB 80 3D CD C5 09 01 01 0F 85 E5 00 00 00 38 1D 37 C6 09 01 0F 85 D9 00 00 00 0F B7 05 9C F7 EF 01 33 D2 66 2B 05 8F F7 EF",true},
    {"saber_target_state_push",0x1dc1e0,"48 8B C4 48 89 58 10 48 89 48 08 57 48 83 EC 60 48 8B 1D E9 FB C5 02 48 63 4B 10 8B 53 14 0F 10 43 18 8D 79 01 3B D7 0F 8D A3 00 00 00 0F 11 40",true},
    {"saber_target_state_pop",0x1dc2f0,"40 53 48 83 EC 40 48 8B 1D E3 FA C5 02 83 7B 10 00 74 3D 48 8B 03 4C 8B 80 F8 00 00 00 8B 43 10 FF C8 48 98 48 8D 0C C0 48 8B 43 08 48 8D 14 C8",true},
    {"saber_target_bind_description",0x1dbe50,"48 89 5C 24 10 55 56 57 41 56 41 57 48 81 EC 80 00 00 00 48 8B 05 A6 91 99 01 48 33 C4 48 89 44 24 70 41 8B D9 48 8D 74 24 20 4D 8B F8 48 8B EA",true},
    {"saber_target_unbind_description",0x1dbf20,"48 89 5C 24 08 48 89 6C 24 10 56 57 41 56 48 81 EC 80 00 00 00 48 8B 05 D4 90 99 01 48 33 C4 48 89 44 24 70 48 8B 35 95 FE C5 02 48 8D 5C 24 20",true},
    {"classic_game_render",0xac47c0,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 20 57 41 54 41 55 41 56 41 57 48 83 EC 60 0F 29 70 C8 BD 01 00 00 00 01 2D 05 2D 3E 02 0F 28 F1 0F 29",true},
    {"classic_player_window",0xbbca64,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8D A8 48 FB FF FF 48 81 EC 90 05 00 00 48 8B 05 7F 85 FB 00 48 33 C4",true},
    {"classic_final_blit",0xb51a14,"48 89 5C 24 10 48 89 74 24 18 55 57 41 56 48 8D 6C 24 B9 48 81 EC F0 00 00 00 48 8B 05 DB 35 02 01 48 33 C4 48 89 45 37 33 C0 48 8B D9 48 89 45",true},
    {"classic_bind_native_surface_views",0xae0e0,"48 89 5C 24 18 41 56 48 83 EC 30 4C 63 C1 4C 8D 35 0B 1F F5 FF 4B 8B 9C C6 10 B9 E3 02 48 85 DB 0F 84 E2 00 00 00 83 F9 08 0F 84 D9 00 00 00 48",true},
    {"classic_surface_rtv_accessor",0x22b7b0,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 41 8B F9 41 8B F0 0F B6 DA 4C 8B D9 E8 20 1E E8 FF 41 8B 93 88 00 00 00 B9 01 00 00 00 45 0F BE 4B",true},
    {"classic_final_quad_draw",0xbf5f08,"89 54 24 10 53 48 83 EC 40 83 64 24 60 00 48 8D 54 24 30 48 89 54 24 28 48 8B D9 48 8B 0D 06 CE 2A 02 41 B9 04 00 00 00 48 8B 15 F9 59 2B 02 45",true},
    {"classic_source_sampler",0xb519a0,"48 89 5C 24 08 4C 89 4C 24 20 57 48 83 EC 30 33 DB 0F B7 F9 66 83 FA 09 77 16 48 0F BF C2 48 8D 1D BB 44 03 01 4C 8D 04 40 4D 03 C0 4A 8B 1C C3",true},
    {"classic_frustum_bounds",0xb8f144,"48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 0F BF 59 38 48 8B F2 0F BF 79 2C 44 0F BF 51 34 44 0F BF 59 30 44 0F BF 49 32 41 8B C3 44 0F BF 41",true},
    {"classic_frustum_build",0xb8f690,"48 8B C4 55 53 56 57 41 54 41 56 41 57 48 8D 68 A1 48 81 EC F0 00 00 00 44 0F BF 51 32 45 8A F9 0F 29 70 B8 49 8B F8 0F 29 78 A8 48 8B F1 44 0F",true},
    {"classic_output_target_initialize",0xae410,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 54 41 55 41 56 41 57 48 81 EC 80 00 00 00 48 8B 05 DA 6B AC 01 48 33 C4 48 89 44 24 78 48 8B 05 4B DC D8 02",true},
}};
inline constexpr std::array<Witness,131> witnesses={{
    {0xbbcf5b,"48 8B BD F0 01 00 00"},
    {0xbbcf62,"49 8B F0"},
    {0xbbcf65,"48 8B DA"},
    {0xbbcf68,"44 0F B7 F9"},
    {0xbbcf86,"4D 8B F1"},
    {0xbbcfdc,"41 8D 44 24 02"},
    {0xbbcfe1,"8D 50 7D"},
    {0xbbd01a,"48 03 CA"},
    {0xbbd021,"48 03 F2"},
    {0xbbd028,"49 2B C4"},
    {0xbbd02b,"75 B7"},
    {0xbbd02d,"48 8B 06"},
    {0xbbd030,"48 89 01"},
    {0xbbd033,"8B 46 08"},
    {0xbbd036,"89 41 08"},
    {0xbbd3aa,"E8 ?? ?? ?? ??"},
    {0xbbcfa0,"0F 11 05 ?? ?? ?? ??"},
    {0xbbcf96,"48 8D 0D ?? ?? ?? ??"},
    {0xb516f6,"E8 ?? ?? ?? ??"},
    {0xb517de,"48 8B 0D ?? ?? ?? ??"},
    {0xb5180e,"48 8B 0D ?? ?? ?? ??"},
    {0xb5183e,"48 8B 0D ?? ?? ?? ??"},
    {0xb518c3,"48 8B 0D ?? ?? ?? ??"},
    {0xb0d82,"48 8B 0D ?? ?? ?? ??"},
    {0xb0e01,"48 8B 0D ?? ?? ?? ??"},
    {0xb0e10,"39 35 ?? ?? ?? ??"},
    {0xb0e1d,"48 8B 15 ?? ?? ?? ??"},
    {0xb0e24,"E8 ?? ?? ?? ??"},
    {0xb0e2e,"E8 ?? ?? ?? ??"},
    {0xb0e48,"48 8B 15 ?? ?? ?? ??"},
    {0xb0e4f,"48 8B 0D ?? ?? ?? ??"},
    {0xb0e56,"E8 ?? ?? ?? ??"},
    {0xb0e8c,"48 8B 0D ?? ?? ?? ??"},
    {0xb0e99,"48 8B 0D ?? ?? ?? ??"},
    {0xb0eba,"48 8B 15 ?? ?? ?? ??"},
    {0xb0f53,"48 8B 05 ?? ?? ?? ??"},
    {0xb0fa0,"48 8B 0D ?? ?? ?? ??"},
    {0xb0fa7,"48 8B 05 ?? ?? ?? ??"},
    {0xb0fae,"48 89 05 ?? ?? ?? ??"},
    {0xb0fb5,"48 89 0D ?? ?? ?? ??"},
    {0xae0e49,"E8 22 08 07 00"},
    {0xae0e6a,"E8 55 CA 05 00"},
    {0xae0e78,"BA 01 00 00 00"},
    {0xae0e7d,"C7 05 B1 26 17 01 01 00 00 00"},
    {0xae0e8a,"E8 35 CA 05 00"},
    {0xae0ea2,"E8 1D CA 05 00"},
    {0xae0eb7,"B9 CE 00 00 00"},
    {0xae0ebc,"E8 03 CA 05 00"},
    {0xae0ec6,"E8 49 0B 07 00"},
    {0xae0ed3,"BA 02 00 00 00"},
    {0xae0ee9,"E8 D6 C9 05 00"},
    {0xae0eee,"E8 E9 0A 0C 00"},
    {0xae0dfc,"80 3D ?? ?? ?? ?? 01"},
    {0xae0e09,"38 1D ?? ?? ?? ??"},
    {0xae0e49,"E8 ?? ?? ?? ??"},
    {0xae0ec6,"E8 ?? ?? ?? ??"},
    {0x1dc1f0,"48 8B 1D ?? ?? ?? ??"},
    {0x1dc2f6,"48 8B 1D ?? ?? ?? ??"},
    {0x1dc356,"E8 ?? ?? ?? ??"},
    {0x1dbf44,"48 8B 35 ?? ?? ?? ??"},
    {0xac47fa,"48 8B 0D ?? ?? ?? ??"},
    {0xac483f,"48 8D 15 ?? ?? ?? ??"},
    {0xac4908,"48 8D 15 ?? ?? ?? ??"},
    {0xbbcc94,"4C 8D 4F 58"},
    {0xbbcc98,"66 44 89 64 24 28"},
    {0xbbcc9e,"4C 8D 85 60 01 00 00"},
    {0xbbcca5,"49 8B D6"},
    {0xbbcca8,"48 89 44 24 20"},
    {0xbbcc0f,"40 38 35 ?? ?? ?? ??"},
    {0xbbcc77,"E8 ?? ?? ?? ??"},
    {0xbbccad,"E8 ?? ?? ?? ??"},
    {0xb51a5c,"E8 ?? ?? ?? ??"},
    {0xb51cb3,"E8 ?? ?? ?? ??"},
    {0xae0e0,"48 89 5C 24 18"},
    {0xae0f5,"4B 8B 9C C6 10 B9 E3 02"},
    {0x22b7b0,"48 89 5C 24 08"},
    {0x22b7b5,"48 89 74 24 10"},
    {0x22b7d0,"41 8B 93 88 00 00 00"},
    {0x22b7dc,"45 0F BE 4B 1A"},
    {0x22b7e7,"44 8D 41 05"},
    {0x22b7ef,"48 8B 80 F8 00 00 00"},
    {0x22b7f8,"48 8B 80 E8 00 00 00"},
    {0x22b7ff,"48 8B 5C 24 30"},
    {0x22b80a,"0F AF 4C 24 50"},
    {0x22b817,"48 8B 74 24 38"},
    {0x22b81f,"48 8B 04 C8"},
    {0x2298f9,"48 89 07"},
    {0x2298f2,"48 8D 05 ?? ?? ?? ??"},
    {0xbf5f08,"89 54 24 10"},
    {0xbf5f11,"83 64 24 60 00"},
    {0xbf5f16,"48 8D 54 24 30"},
    {0xbf5f1b,"48 89 54 24 28"},
    {0xbf5f3a,"83 64 24 20 00"},
    {0xbf5f3f,"48 8B 01"},
    {0xbf5f42,"FF 50 70"},
    {0xbf5f49,"44 8B 44 24 58"},
    {0xbf5f51,"48 8B 4C 24 30"},
    {0xbf5f70,"48 8B 01"},
    {0xbf5f73,"FF 50 78"},
    {0xbf5f7d,"48 8D 54 24 60"},
    {0xbf5f82,"48 89 54 24 28"},
    {0xbf5f8e,"48 8D 54 24 58"},
    {0xbf5f93,"48 89 54 24 20"},
    {0xbf5f9a,"48 8B 01"},
    {0xbf5f9d,"44 8D 42 01"},
    {0xbf5fa1,"FF 90 90 00 00 00"},
    {0xbf5fb3,"48 8B 01"},
    {0xbf5fb6,"FF 90 C0 00 00 00"},
    {0xbf5fd5,"48 8B 01"},
    {0xbf5fd8,"41 8D 50 04"},
    {0xbf5fdc,"FF 50 68"},
    {0xbf5f23,"48 8B 0D ?? ?? ?? ??"},
    {0xbf5f5f,"48 8B 0D ?? ?? ?? ??"},
    {0xbf5f76,"48 8B 0D ?? ?? ?? ??"},
    {0xbf5fa7,"48 8B 0D ?? ?? ?? ??"},
    {0xbf5fcb,"48 8B 0D ?? ?? ?? ??"},
    {0xb519be,"48 8D 1D ?? ?? ?? ??"},
    {0xb519e3,"E8 ?? ?? ?? ??"},
    {0xb519e8,"48 8B 0D ?? ?? ?? ??"},
    {0xae455,"48 8B 98 00 05 00 00"},
    {0xae462,"FF 90 D8 00 00 00"},
    {0xae486,"48 8B CB"},
    {0xae490,"E8 5B F1 FF FF"},
    {0xae49a,"48 8B 88 E0 00 00 00"},
    {0xae4c3,"41 BD 01 00 00 00"},
    {0xae4cd,"41 8B ED"},
    {0xae601,"49 89 B4 DF 10 B9 E3 02"},
    {0xae6ce,"FF C5"},
    {0xae6d0,"83 FD 09"},
    {0xae43e,"48 8B 05 ?? ?? ?? ??"},
    {0xae489,"48 89 3D ?? ?? ?? ??"},
}};
inline constexpr std::array<Relative,52> relatives={{
    {0xbbd3aa,5,1,0xb0d40},
    {0xbbcfa0,7,3,0x29af2c4},
    {0xbbcf96,7,3,0x29af318},
    {0xb516f6,5,1,0xaeb00},
    {0xb517de,7,3,0x2ea2d30},
    {0xb5180e,7,3,0x2ea2d30},
    {0xb5183e,7,3,0x2ea2d30},
    {0xb518c3,7,3,0x2ea2d30},
    {0xb0d82,7,3,0x2ea2d90},
    {0xb0e01,7,3,0x2e3bde0},
    {0xb0e10,6,2,0x1b7aa84},
    {0xb0e1d,7,3,0x2e3b918},
    {0xb0e24,5,1,0x1dbf20},
    {0xb0e2e,5,1,0x1dc1e0},
    {0xb0e48,7,3,0x2e3b920},
    {0xb0e4f,7,3,0x2e3bde0},
    {0xb0e56,5,1,0x1dbe50},
    {0xb0e8c,7,3,0x2e3b918},
    {0xb0e99,7,3,0x2e3b918},
    {0xb0eba,7,3,0x2e3b918},
    {0xb0f53,7,3,0x2e3bde0},
    {0xb0fa0,7,3,0x2e3b918},
    {0xb0fa7,7,3,0x2e3b920},
    {0xb0fae,7,3,0x2e3b918},
    {0xb0fb5,7,3,0x2e3b920},
    {0xae0dfc,7,2,0x1b7d3d0},
    {0xae0e09,6,2,0x1b7d446},
    {0xae0e49,5,1,0xb51670},
    {0xae0ec6,5,1,0xb51a14},
    {0x1dc1f0,7,3,0x2e3bde0},
    {0x1dc2f6,7,3,0x2e3bde0},
    {0x1dc356,5,1,0x1dbe50},
    {0x1dbf44,7,3,0x2e3bde0},
    {0xac47fa,7,3,0x2ea2d90},
    {0xac483f,7,3,0x2e9fe80},
    {0xac4908,7,3,0x2e9fe80},
    {0xbbcc0f,7,3,0x1b7d446},
    {0xbbcc77,5,1,0xbbcf30},
    {0xbbccad,5,1,0xbbcf30},
    {0xb51a5c,5,1,0xb519a0},
    {0xb51cb3,5,1,0xbf5f08},
    {0x2298f2,7,3,0x17fb608},
    {0xbf5f23,7,3,0x2ea2d30},
    {0xbf5f5f,7,3,0x2ea2d30},
    {0xbf5f76,7,3,0x2ea2d30},
    {0xbf5fa7,7,3,0x2ea2d30},
    {0xbf5fcb,7,3,0x2ea2d30},
    {0xb519be,7,3,0x1b85e80},
    {0xb519e3,5,1,0xb51670},
    {0xb519e8,7,3,0x2ea2d30},
    {0xae43e,7,3,0x2e3c090},
    {0xae489,7,3,0x1b85e78},
}};
inline constexpr std::array<Pointer,1> pointers={{
    {0x17fb6e0,0x22b7b0},
}};
inline constexpr uint32_t classic_view_render=0xbbcf30;
inline constexpr uint32_t classic_render_target_select=0xb51670;
inline constexpr uint32_t classic_saber_target_route=0xaeb00;
inline constexpr uint32_t classic_postprocess_ping_pong=0xb0d40;
inline constexpr uint32_t classic_outer_output=0xae0df4;
inline constexpr uint32_t saber_target_state_push=0x1dc1e0;
inline constexpr uint32_t saber_target_state_pop=0x1dc2f0;
inline constexpr uint32_t saber_target_bind_description=0x1dbe50;
inline constexpr uint32_t saber_target_unbind_description=0x1dbf20;
inline constexpr uint32_t classic_game_render=0xac47c0;
inline constexpr uint32_t classic_player_window=0xbbca64;
inline constexpr uint32_t classic_final_blit=0xb51a14;
inline constexpr uint32_t classic_bind_native_surface_views=0xae0e0;
inline constexpr uint32_t classic_surface_rtv_accessor=0x22b7b0;
inline constexpr uint32_t classic_final_quad_draw=0xbf5f08;
inline constexpr uint32_t classic_source_sampler=0xb519a0;
inline constexpr uint32_t classic_frustum_bounds=0xb8f144;
inline constexpr uint32_t classic_frustum_build=0xb8f690;
inline constexpr uint32_t classic_output_target_initialize=0xae410;
}
namespace classic_first_person_projection {
inline constexpr std::array<Entry,2> entries={{
    {"first_person_classic_lens",0xae1af0,"40 53 48 83 EC 20 0F 28 C8 8A DA 0F 2E 0D 9E E3 E6 00 7A 02 74 45 0F BF 05 A9 EA",true},
    {"first_person_classic_lens_math",0xb8ee3c,"48 8B C4 53 48 81 EC A0 00 00 00 41 0F BF 51 32 48 8B D9 0F 29 70 E8",true},
}};
inline constexpr std::array<Witness,21> witnesses={{
    {0xc1767f,"F6 03 80 74 30 40 84 F6 75 2B 8B CF E8 CC A4 EC FF F3 0F 10 05 14 7E D3 00 33 D2 E8 51 A4 EC FF F3 0F 10 0D 61 5D F6 00 F3 0F 10 05 55 5D F6 00 E8 04 A4 EC FF"},
    {0xc1599d,"F6 03 80 74 24 F3 0F 10 05 02 9B D3 00 33 D2 E8 3F C1 EC FF F3 0F 10 0D 4F 7A F6 00 F3 0F 10 05 43 7A F6 00 E8 F2 C0 EC FF"},
    {0xbf4420,"F6 03 80 74 33 40 84 FF 75 2E 33 C9 E8 2B D7 EE FF F3 0F 10 05 73 B0 D5 00 33 D2 E8 B0 D6 EE FF F3 0F 10 0D C0 8F F8 00 F3 0F 10 05 B4 8F F8 00 E8 63 D6 EE FF"},
    {0xc12340,"45 84 F6 79 0F F3 0F 10 05 5F D1 D3 00 33 D2 E8 9C F7 EC FF"},
    {0xc12b3e,"45 84 F6 79 11 F3 0F 10 05 61 C9 D3 00 B2 01 E8 9E EF EC FF"},
    {0xc19697,"F6 00 80 74 25 38 1D FF 23 29 02 75 1D 8D 4B 02 E8 B0 84 EC FF 33 D2 0F 57 C0 E8 3A 84 EC FF 0F 57 C9 0F 57 C0 E8 F7 83 EC FF"},
    {0xae1b06,"0F BF 05 A9 EA EF 01 4C 8D 0D 74 EA EF 01 0F BF 0D 9F EA EF 01 2B C8 0F BF 05 90 EA EF 01 66 0F 6E D1 0F BF 0D 89 EA EF 01 2B C8 0F 5B D2 66 0F 6E C1 48 8D 0D 9D EA EF 01 0F 5B C0 F3 0F 5E D0 E8 F1 D2 0A 00"},
    {0xc1769a,"E8 51 A4 EC FF"},
    {0xc159ac,"E8 3F C1 EC FF"},
    {0xbf443b,"E8 B0 D6 EE FF"},
    {0xc1234f,"E8 9C F7 EC FF"},
    {0xc12b4d,"E8 9E EF EC FF"},
    {0xae1b46,"E8 F1 D2 0A 00"},
    {0xae1afb,"0F 2E 0D 9E E3 E6 00"},
    {0xc17690,"F3 0F 10 05 14 7E D3 00"},
    {0xb8ee92,"0F 2E 0D 07 BA CB 00 66 44 0F 6E EA 45 0F 5B ED 45 0F 5B E4 7A 67 75 65"},
    {0xb8ef0f,"0F 2E 0D 82 49 CF 00 7A 67 75 65 F3 0F 10 05 7E D5 02 03 F3 0F 10 0D 7A D5 02 03"},
    {0xb8eff3,"F3 0F 59 C7 F3 0F 5E D1 F3 0F 5E D8 F3 0F 11 93 44 01 00 00 F3 0F 11 9B 58 01 00 00"},
    {0xb8f045,"F3 44 0F 11 83 64 01 00 00 F3 44 0F 11 8B 78 01 00 00 F3 0F 11 93 84 01 00 00"},
    {0xb8ee92,"0F 2E 0D 07 BA CB 00"},
    {0xb8ef0f,"0F 2E 0D 82 49 CF 00"},
}};
inline constexpr std::array<Relative,10> relatives={{
    {0xc1769a,5,1,0xae1af0},
    {0xc159ac,5,1,0xae1af0},
    {0xbf443b,5,1,0xae1af0},
    {0xc1234f,5,1,0xae1af0},
    {0xc12b4d,5,1,0xae1af0},
    {0xae1b46,5,1,0xb8ee3c},
    {0xae1afb,7,3,0x194fea0},
    {0xc17690,8,4,0x194f4ac},
    {0xb8ee92,7,3,0x184a8a0},
    {0xb8ef0f,7,3,0x1883898},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t first_person_classic_lens=0xae1af0;
inline constexpr uint32_t first_person_classic_lens_math=0xb8ee3c;
}
namespace comfort {
inline constexpr std::array<Entry,1> entries={{
    {"motion_blur_draw",0x446580,"48 8B C4 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 58 FC FF FF 48 81 EC 70 04 00 00 48 C7 45 D0 FE FF FF FF",true},
}};
inline constexpr std::array<Witness,5> witnesses={{
    {0x4465e7,"48 8B 05 EA 57 9F 02 80 B8 23 02 00 00 00 0F 84 29 06 00 00 49 8B D1 E8 0D FB FF FF"},
    {0x446603,"49 63 87 20 02 00 00 48 6B F0 7C"},
    {0x446110,"48 8B C4 48 89 58 18 48 89 78 20 55 48 8D 6C 24 80 48 81 EC 80 01 00 00"},
    {0x45107a,"E8 01 55 FF FF"},
    {0x4465fe,"E8 0D FB FF FF"},
}};
inline constexpr std::array<Relative,2> relatives={{
    {0x45107a,5,1,0x446580},
    {0x4465fe,5,1,0x446110},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t motion_blur_draw=0x446580;
}
namespace contact {
inline constexpr std::array<Entry,6> entries={{
    {"contact_biped_tick",0xbaf258,"48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 83 EC 20 4C 8B 05 CD 2F 09 01",true},
    {"contact_collision",0xb913fc,"48 8B C4 48 89 58 20 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 F8 FB FF FF 48 81 EC D0 04 00 00",true},
    {"contact_object_collision",0xb9105c,"40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 F8 FB FF FF 48 81 EC 08 05 00 00 48 8B 05 91 3F FE 00",true},
    {"contact_resolver",0xb93c8c,"48 89 5C 24 10 48 89 74 24 20 55 57 41 56 48 8D 6C 24 C1 48 81 EC A0 00 00 00 48 8B 05 63 13 FE 00",true},
    {"contact_player_melee",0xb0c388,"48 8B C4 48 89 58 20 55 56 57 41 54 41 55 41 56 41 57 48 8D 68 A1 48 81 EC F0 00 00 00 0F 29 70 B8",true},
    {"contact_damage",0xb9ea28,"48 8B C4 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 18 FF FF FF 48 81 EC A8 01 00 00 0F 29 70 A8 0F 29 78 98 44 0F 29 40 88 44 0F 29 88 78 FF FF FF 44 0F 29 90 68 FF FF FF 44 0F 29 98 58 FF FF FF 48 8B 05 9F 65 FD 00",true},
}};
inline constexpr std::array<Witness,23> witnesses={{
    {0xbaf813,"41 8A C4"},
    {0xbaf796,"E8 ED CB F5 FF"},
    {0xb9146b,"C7 43 14 00 00 80 3F"},
    {0xb91271,"B8 03 00 00 00 F3 0F 11 4B 14 66 89 03"},
    {0xb91210,"89 7B 38"},
    {0xb912e7,"66 89 43 34"},
    {0xb93cf0,"B9 E9 00 10 00"},
    {0xb93d0c,"66 83 7D EF FF"},
    {0xb93d9f,"B3 01 8A C3"},
    {0xb93cff,"E8 F8 D6 FF FF"},
    {0xb0c428,"41 3B F8 74 0F"},
    {0xb0c489,"4C 63 5E 34"},
    {0xb0c7e6,"33 C9 66 39 08 0F 85 BE 00 00 00"},
    {0xb0c89d,"48 8D 4D A7 8B D7 E8 80 21 09 00"},
    {0xb0c955,"44 88 A3 69 02 00 00"},
    {0xb0c432,"E8 6D C5 02 00"},
    {0xb0c462,"E8 45 FB FF FF"},
    {0xb0c4b9,"E8 1E 98 FF FF"},
    {0xb0c8a3,"E8 80 21 09 00"},
    {0xb0c950,"E8 D3 20 09 00"},
    {0xb9eb6f,"44 39 57 10 74 71 8B 4F 10 41"},
    {0xb9f028,"4C 8D 47 38"},
    {0xb9f40a,"48 8D 57 2C"},
}};
inline constexpr std::array<Relative,7> relatives={{
    {0xbaf796,5,1,0xb0c388},
    {0xb93cff,5,1,0xb913fc},
    {0xb0c432,5,1,0xb389a4},
    {0xb0c462,5,1,0xb0bfac},
    {0xb0c4b9,5,1,0xb05cdc},
    {0xb0c8a3,5,1,0xb9ea28},
    {0xb0c950,5,1,0xb9ea28},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t contact_biped_tick=0xbaf258;
inline constexpr uint32_t contact_collision=0xb913fc;
inline constexpr uint32_t contact_object_collision=0xb9105c;
inline constexpr uint32_t contact_resolver=0xb93c8c;
inline constexpr uint32_t contact_player_melee=0xb0c388;
inline constexpr uint32_t contact_damage=0xb9ea28;
}
namespace continuous_target {
inline constexpr std::array<Entry,1> entries={{
    {"continuous_target_query",0xb683ec,"40 53 55 56 57 41 54 41 55 41 56 41 57 B8 68 14 00 00 E8 5D EA A9 00 48 2B E0 48 8B 05 03 CC 00 01 48 33 C4 48 89 84 24 50 14 00 00 48 8B BC 24 D8 14 00 00 48 8B F1 48 8B CA 44 89 4C 24 40 45",true},
}};
inline constexpr std::array<Witness,2> witnesses={{
    {0xb680f8,"E8 EF 02 00 00"},
    {0xb6839b,"E8 4C 00 00 00"},
}};
inline constexpr std::array<Relative,2> relatives={{
    {0xb680f8,5,1,0xb683ec},
    {0xb6839b,5,1,0xb683ec},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t continuous_target_query=0xb683ec;
}
namespace controls {
inline constexpr std::array<Entry,1> entries={{
    {"input_angle_delta",0xa99c1c,"48 8B C4 48 89 58 10 89 48 08 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 B0 48 81 EC 50 01 00 00 48 8B 3D 2C 62 2F 02",true},
}};
inline constexpr std::array<Witness,5> witnesses={{
    {0xa99648,"F3 0F 10 95 10 08 00 00 41 8B CC F3 0F 10 8D 0C 08 00 00 E8 BC 05 00 00"},
    {0xa99c91,"44 0F 28 FA 48 63 C1 48 6B D8 58"},
    {0xa99d3d,"F3 0F 58 74 3B 1C F3 0F 11 74 3B 1C"},
    {0xa99c3d,"48 8B 3D 2C 62 2F 02"},
    {0xa9965b,"E8 BC 05 00 00"},
}};
inline constexpr std::array<Relative,2> relatives={{
    {0xa99c3d,7,3,0x2d8fe70},
    {0xa9965b,5,1,0xa99c1c},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t input_angle_delta=0xa99c1c;
}
namespace first_person {
inline constexpr std::array<Entry,4> entries={{
    {"first_person_prepare",0xb29698,"48 8B C4 48 89 58 10 48 89 68 18 48 89 70 20 57 41 54 41 55 41 56 41 57 48 81 EC F0 08 00 00 0F 29 70 C8 0F 29 78 B8",true},
    {"first_person_graph_palette",0xc43c14,"48 89 5C 24 18 48 89 74 24 20 55 57 41 54 41 56 41 57 48 8D 6C 24 E0 48 81 EC 20 01 00 00 48 8B 05 D7 13 F3 00",true},
    {"first_person_dispatch",0xb27510,"40 53 48 83 EC 20 B9 11 00 00 00 E8 88 AB FF FF 0F B7 0D 91 7D E8 01 84 C0 0F 94 C0 41 83 C9 FF 66 41 3B C9 74 79 84 C0 74 75 48 0F BF C1 48 69",true},
    {"first_person_cached_tag_get",0xa9b648,"48 8B 05 61 99 19 01 48 0F BF D1 48 C1 E2 05 48 63 4C 02 14 33 C0 85 C9 74 11 48 8B C1 48 2B 05 A4 7D 40 02 48 03 05 9D 17 30 02 C3",false},
}};
inline constexpr std::array<Witness,25> witnesses={{
    {0xb2975d,"48 69 FE 94 1E 00 00"},
    {0xb29d75,"48 8D 97 88 10 00 00"},
    {0xb2976f,"48 03 3D 1A 36 27 02"},
    {0xb29d88,"E8 87 9E 11 00"},
    {0xb29d81,"4C 8D 0D 3C 55 E8 01"},
    {0xb29d6a,"48 8D 05 5F 55 E8 01"},
    {0xb29d57,"48 8D 05 7E 55 E8 01"},
    {0xc43c74,"44 39 7F 68"},
    {0xc43ca5,"48 63 47 6C"},
    {0xc43cbe,"49 C1 E2 06"},
    {0xc43cd1,"49 0F BF 42 24 48 6B D8 34 48 03 DE"},
    {0xc43d06,"4D 6B C0 34"},
    {0xc43d22,"45 0F B7 42 20 66 41 83 F8 FF"},
    {0xc43d3c,"41 0F B7 4A 22 66 83 F9 FF"},
    {0xc43c46,"E8 FD 79 E5 FF"},
    {0xc43ca9,"48 2B 05 60 F7 25 02"},
    {0xc43cb0,"48 03 05 59 91 15 02"},
    {0xb2753e,"48 69 D0 94 1E 00 00"},
    {0xb27520,"0F B7 0D 91 7D E8 01"},
    {0xb27545,"48 03 15 44 58 27 02"},
    {0xb275aa,"E8 E9 20 00 00"},
    {0xa9b64f,"48 0F BF D1 48 C1 E2 05 48 63 4C 02 14"},
    {0xa9b648,"48 8B 05 61 99 19 01"},
    {0xa9b665,"48 2B 05 A4 7D 40 02"},
    {0xa9b66c,"48 03 05 9D 17 30 02"},
}};
inline constexpr std::array<Relative,14> relatives={{
    {0xb2976f,7,3,0x2d9cd90},
    {0xb29d88,5,1,0xc43c14},
    {0xb29d81,7,3,0x29af2c4},
    {0xb29d6a,7,3,0x29af2d0},
    {0xb29d57,7,3,0x29af2dc},
    {0xc43c46,5,1,0xa9b648},
    {0xc43ca9,7,3,0x2ea3410},
    {0xc43cb0,7,3,0x2d9ce10},
    {0xb27520,7,3,0x29af2b8},
    {0xb27545,7,3,0x2d9cd90},
    {0xb275aa,5,1,0xb29698},
    {0xa9b648,7,3,0x1c34fb0},
    {0xa9b665,7,3,0x2ea3410},
    {0xa9b66c,7,3,0x2d9ce10},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t first_person_prepare=0xb29698;
inline constexpr uint32_t first_person_graph_palette=0xc43c14;
inline constexpr uint32_t first_person_dispatch=0xb27510;
inline constexpr uint32_t first_person_cached_tag_get=0xa9b648;
}
namespace first_person_aim {
inline constexpr std::array<Entry,9> entries={{
    {"shot_adjust_modern",0xb00880,"48 8B C4 55 53 56 57 41 54 41 56 41 57 48 8D 68 C1 48 81 EC D0 00 00 00 0F 29 70 B8 0F 29 78 A8 44 0F 29 40 98 44 0F 29 48 88 44 0F 29 90 78 FF FF FF 44 0F 29 5C 24 70",true},
    {"shot_adjust_legacy",0xb00740,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 44 0F B7 D1 49 8B E9 49 8B D8 8B F9 48 8B F2",true},
    {"shot_weapon_trigger",0xb7a374,"48 89 5C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 C0 E1 FF FF B8 40 1F 00 00",true},
    {"shot_weapon_owner",0xb77814,"48 89 5C 24 08 57 48 83 EC 20 0F B7 C9 83 CB FF 48 8D 14 49 48 8B 0D 19 AA 0C 01",true},
    {"shot_object_try_get",0xb389a4,"40 53 48 83 EC 20 8B DA 8B D1 48 8B 0D 93 98 10 01 E8 16 2F 08 00 4C 8B D8 33 C0 4D 85 DB 74 28 41 0F B6 4B",true},
    {"shot_local_fp_record",0xb27510,"40 53 48 83 EC 20 B9 11 00 00 00 E8 88 AB FF FF 0F B7 0D 91 7D E8 01 84 C0 0F 94 C0 41 83 C9 FF 66 41 3B C9 74 79 84 C0 74 75 48 0F BF C1 48 69",true},
    {"shot_unit_origin",0xb04d00,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC A0 00 00 00 4C 8B 0D 26 D5 13 01 33 DB 48 8B 2D CD 80 29 02",true},
    {"shot_player_assist",0xb67b00,"48 8B C4 48 89 58 18 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 A0 48 81 EC 60 01 00 00 0F 29 70 B8 0F 29 78 A8 44 0F 29 40 98 44 0F 29 48 88",true},
    {"shot_assist_director_ray",0xb14f14,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 57 48 83 EC 20 48 8B EA 49 8B F0 48 8D 50 20 8B D9 E8 37 00 00 00",true},
}};
inline constexpr std::array<Witness,37> witnesses={{
    {0xb00900,"80 7D 77 00 74 22 41 83 FF FF 49 8D 86 50 02 00 00 B9 1C 02 00 00 48 0F 44 C1 F2 0F 10 00 F2 0F 11 07 8B 40 08 89 47 08"},
    {0xb008fb,"E8 00 44 00 00"},
    {0xb00b38,"E8 4F 31 09 00"},
    {0xb00b61,"E8 32 78 03 00"},
    {0xb00775,"80 7C 24 68 00 74 35 4B 63 54 9A 08 B8 1C 02 00 00 48 8B 0D 6B C6 29 02 48 81 C1 50 02 00 00 48 03 CA 43 83 7C 9A 08 FF 48 0F 44 C8 F2 0F 10 01 F2 41 0F 11 00 8B 41 08 41 89 40 08"},
    {0xb0083e,"F3 0F 10 54 24 24 F3 0F 59 53 04 48 8B 74 24 50 F3 0F 10 4C 24 20 F3 0F 59 0B F3 0F 10 44 24 28 F3 0F 59 43 08 48 8B 5C 24 40 F3 0F 58 D1 F3 0F 58 D0 F3 0F 11 55 00 48 8B 6C 24 48"},
    {0xb007bf,"E8 3C 45 00 00"},
    {0xb00839,"E8 5A 7B 03 00"},
    {0xb7a741,"F7 03 00 40 00 00"},
    {0xb7a64d,"44 8B B6 F8 01 00 00"},
    {0xb7a545,"E8 CA D2 FF FF"},
    {0xb7a608,"E8 97 E3 FB FF"},
    {0xb7a791,"E8 EA 60 F8 FF"},
    {0xb7a853,"E8 E8 5E F8 FF"},
    {0xb77847,"48 81 C2 0C 01 00 00"},
    {0xb77858,"8B 3A 3B FB 74 10 8D 53 04 8B CF E8 3C 11 FC FF 48 85 C0 0F 45 DF"},
    {0xb77828,"48 8B 0D 19 AA 0C 01"},
    {0xb77840,"48 8B 15 B1 55 22 02"},
    {0xb77863,"E8 3C 11 FC FF"},
    {0xb389c4,"41 0F B6 4B 03 0F A3 CB 73 1E 4C 8B 05 23 44 26 02 49 63 53 08 49 83 C0 34 4C 03 C2 41 83 7B 08 FF 4C 0F 44 C0"},
    {0xb389ae,"48 8B 0D 93 98 10 01"},
    {0xb389b5,"E8 16 2F 08 00"},
    {0xb389ce,"4C 8B 05 23 44 26 02"},
    {0xb2753e,"48 69 D0 94 1E 00 00"},
    {0xb2754c,"44 39 4A 04 74 5D 44 39 4A 08"},
    {0xb27545,"48 03 15 44 58 27 02"},
    {0xb04d61,"8B 8E D8 00 00 00"},
    {0xb04d6a,"41 3B CF 0F 85 A4 00 00 00"},
    {0xb04d5c,"E8 E7 68 F9 FF"},
    {0xb67bd3,"8B 4F 64 4C 8D 44 24 50 48 8D 55 88"},
    {0xb67e9e,"F2 0F 10 44 24 50 8B 44 24 58 F2 0F 11 03 89 43 08"},
    {0xb67bdf,"E8 30 D3 FA FF"},
    {0xb14f39,"0F B7 F8 4C 8B C6 48 8B D5 8B CB 66 85 C0 75 07"},
    {0xb14f5a,"0F B7 C7"},
    {0xb14f34,"E8 37 00 00 00"},
    {0xb14f49,"E8 26 D3 13 00"},
    {0xb14f50,"E8 23 DC 13 00"},
}};
inline constexpr std::array<Relative,21> relatives={{
    {0xb008fb,5,1,0xb04d00},
    {0xb00b38,5,1,0xb93c8c},
    {0xb00b61,5,1,0xb38398},
    {0xb007bf,5,1,0xb04d00},
    {0xb00839,5,1,0xb38398},
    {0xb7a545,5,1,0xb77814},
    {0xb7a608,5,1,0xb389a4},
    {0xb7a791,5,1,0xb00880},
    {0xb7a853,5,1,0xb00740},
    {0xb77828,7,3,0x1c42248},
    {0xb77840,7,3,0x2d9cdf8},
    {0xb77863,5,1,0xb389a4},
    {0xb389ae,7,3,0x1c42248},
    {0xb389b5,5,1,0xbbb8d0},
    {0xb389ce,7,3,0x2d9cdf8},
    {0xb27545,7,3,0x2d9cd90},
    {0xb04d5c,5,1,0xa9b648},
    {0xb67bdf,5,1,0xb14f14},
    {0xb14f34,5,1,0xb14f70},
    {0xb14f49,5,1,0xc52274},
    {0xb14f50,5,1,0xc52b78},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t shot_adjust_modern=0xb00880;
inline constexpr uint32_t shot_adjust_legacy=0xb00740;
inline constexpr uint32_t shot_weapon_trigger=0xb7a374;
inline constexpr uint32_t shot_weapon_owner=0xb77814;
inline constexpr uint32_t shot_object_try_get=0xb389a4;
inline constexpr uint32_t shot_local_fp_record=0xb27510;
inline constexpr uint32_t shot_unit_origin=0xb04d00;
inline constexpr uint32_t shot_player_assist=0xb67b00;
inline constexpr uint32_t shot_assist_director_ray=0xb14f14;
}
namespace first_person_particles {
inline constexpr std::array<Entry,3> entries={{
    {"first_person_particle_draw",0x6770d0,"40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 58 E6 FF FF B8 A8 1A 00 00 E8 71 FD F8 00 48 2B",true},
    {"first_person_particle_commit",0x202b10,"48 89 5C 24 20 56 48 83 EC 60 48 8B 05 EF 24 97 01 48 33 C4 48 89 44 24 58",true},
    {"first_person_particle_buffer_allocate",0x20a190,"48 89 5C 24 20 55 41 54 41 56 48 83 EC 20 44 0F B6 51 44 4C 8B F2 45 0F B7 E0 48 8B D9 BA 00 10",true},
}};
inline constexpr std::array<Witness,22> witnesses={{
    {0x677380,"33 D2 41 B8 44 0B 00 00 48 8D 8D 50 01 00 00 E8 9B C2 D1 00"},
    {0x677593,"4B 8D 0C B6 48 C1 E1 06"},
    {0x6776ce,"41 8B 85 E8 00 00 00 42 89 84 39 A0 00 00 00"},
    {0x67869b,"44 0F B7 C0 48 8D 55 D0 49 8B 8F A0 01 00 00 E8 E1 1A B9 FF"},
    {0x6786e3,"48 8D 88 50 01 00 00 48 8B D6 41 B8 40 0B 00 00 E8 B9 E8 F8 00"},
    {0x678786,"48 8B 4D D0 48 8B 01 41 B0 01 48 8B D3 FF 50 08"},
    {0x678799,"4C 8D 4D D0 BA 03 00 00 00 44 8D 42 04 48 8B CB FF 90 C0 00 00 00 45"},
    {0x671c39,"F3 44 0F 10 05 B6 F2 18 01"},
    {0x671db4,"0F 57 FF"},
    {0x67277c,"48 8B 43 20"},
    {0x672790,"F7 40 28 00 00 00 10 74 3A"},
    {0x672799,"48 8B 80 80 00 00 00 48 8D 0D A1 B9 17 01 48 85 C0 48 8D 15 57 51 1B 01 48 0F 45 C8"},
    {0x6727c0,"0F B6 04 39 48 FF C7 3A 44 3A FF 75 29 48 83 FF 07 75 ED F3 0F 11 BB E8 00 00 00"},
    {0x6727f6,"F3 44 0F 11 83 E8 00 00 00 EB DA"},
    {0x202b29,"8B 41 0C 48 8B F2 48 8B D9 39 41 08 0F 8D CF 00 00 00"},
    {0x202b5e,"48 63 53 08 4C 8D 4C 24 40 48 8B 8E E8 0C 00 00 8B C2 C1 E0 04 33"},
    {0x202b7c,"8B 43 0C C1 E0 04 89 44 24 4C"},
    {0x202bad,"48 C1 E0 04 48 03 43 18 89 7C 24 30 89 7C 24 28 48 89 44 24 20 41 FF 92 A0 03 00 00 EB 2E 48 8B 8E E0 0C"},
    {0x202bcb,"48 8B 8E E0 0C 00 00 33 FF 48 8B 43 18 45 33 C9 48 8B 53 28 45 33 C0 89 7C 24 30 4C 8B 11 89 7C 24 28 48 89 44 24 20 41 FF 92 80 01 00 00"},
    {0x202bf9,"8B 43 10 89 7B 0C 48 8B BC 24 80 00 00 00 89 43 08"},
    {0x202c80,"39 51 08 44 8B CA 48 63 C2 44 0F 4C 49 08 44 03 C2 44 39 41 0C 44 89 49 08 44 0F 4F 41 0C 48 C1 E0 04 44 89 41 0C 48 03 41 18 C3"},
    {0x20a276,"66 41 89 6E 08 48 8B 43 28 48 63 53 38 48 8B 08 48 8B 04 D1 49 89 06 66 45 89 66 0A 66 44 01 63 3C 49 8B 0E 45 0F BF 46 0A 41 0F BF 56 08 48 8B 01 48 8B 5C 24 58 48 83 C4 20 41 5E 41 5C 5D"},
}};
inline constexpr std::array<Relative,0> relatives={{
}};
inline constexpr std::array<Pointer,2> pointers={{
    {0x17f8c80,0x202b10},
    {0x17f8c90,0x202c80},
}};
inline constexpr uint32_t first_person_particle_draw=0x6770d0;
inline constexpr uint32_t first_person_particle_commit=0x202b10;
inline constexpr uint32_t first_person_particle_buffer_allocate=0x20a190;
}
namespace first_person_projection {
inline constexpr std::array<Entry,3> entries={{
    {"first_person_glt_constants",0x264080,"48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 81 EC 80 00 00 00 48 8B AC 24 E8 00 00 00",true},
    {"first_person_zfill_constants",0x26ff00,"4D 85 C0 74 1B 41 F7 40 28 00 00 00 10 74 11 F3 0F 10 05 E1 0F 59 01 0F C6 C0 00 0F 11 42 20 C3 0F 57 C0 0F C6 C0 00 0F 11 42 20 C3",false},
    {"first_person_sfx_constants",0x26e960,"40 55 48 8B EC 48 83 EC 10 4C 8B 4D 48 41 0F 10 41 18 0F 11 45 F0 4D 85 C0 0F 84 CE 00 00 00",true},
}};
inline constexpr std::array<Witness,4> witnesses={{
    {0x26437d,"41 F7 45 28 00 00 00 10 74 05 0F 28 C6 EB 03 0F 57 C0 0F C6 C0 00 0F 11 87 70 01 00 00"},
    {0x7adf0,"48 8B 46 10 48 8B 88 98 01 00 00 48 8B 04 0A 81 48 28 00 00 00 10"},
    {0x26ff00,"4D 85 C0 74 1B 41 F7 40 28 00 00 00 10 74 11 F3 0F 10 05 E1 0F 59 01 0F C6 C0 00 0F 11 42 20 C3 0F 57 C0 0F C6 C0 00 0F 11 42 20 C3"},
    {0x26ecc2,"4D 85 C0 74 0A 41 F7 40 28 00 00 00 10 75 03 0F 57 D2 0F C6 D2 00 0F 11 52 70 48 83 C4 10 5D C3"},
}};
inline constexpr std::array<Relative,0> relatives={{
}};
inline constexpr std::array<Pointer,3> pointers={{
    {0x17ffa48,0x264080},
    {0x1800cf8,0x26ff00},
    {0x1800b38,0x26e960},
}};
inline constexpr uint32_t first_person_glt_constants=0x264080;
inline constexpr uint32_t first_person_zfill_constants=0x26ff00;
inline constexpr uint32_t first_person_sfx_constants=0x26e960;
}
namespace first_person_skin {
inline constexpr std::array<Entry,1> entries={{
    {"first_person_saber_bone_convert",0x77e70,"48 83 EC 68 F3 0F 10 69 14 33 C0 F3 0F 10 59 20 F3 0F 10 49 24 F3 0F 10 51 10 F3 0F 10 61 18",true},
}};
inline constexpr std::array<Witness,4> witnesses={{
    {0x8b96f,"48 6B C8 34 48 81 C1 0C 02 00 00 49 03 CF"},
    {0x77f19,"F3 0F 11 32"},
    {0x77f5c,"C7 42 3C 00 00 80 3F"},
    {0x8b97d,"E8 EE C4 FE FF"},
}};
inline constexpr std::array<Relative,1> relatives={{
    {0x8b97d,5,1,0x77e70},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t first_person_saber_bone_convert=0x77e70;
}
namespace first_person_visibility {
inline constexpr std::array<Entry,4> entries={{
    {"first_person_visibility_prepare",0x2cfe50,"48 8B C4 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 D8 FE FF FF 48 81 EC F0 01 00 00 48 C7 44 24 78 FE FF FF FF",true},
    {"first_person_visibility_scheduler",0x7b2e0,"48 83 EC 28 0F B6 05 06 06 DC 02 84 C0 0F 85 79 01 00 00 48 89 7C 24 20 33 FF 8B CF 39 0D EE 9D A8 02 7E 2B 8B D7 66 66 0F 1F 84 00 00 00 00 00 48 8B",true},
    {"first_person_visibility_bridge_branch",0x7afb1,"48 8B 05 20 0E DC 02 83 B8 38 02 00 00 00 0F 84 BB 00 00 00 C6 46 1C 00 C6 46 1E 00",false},
    {"first_person_visibility_submit",0x4aa740,"40 55 56 41 56 41 57 48 8D 6C 24 D8 48 81 EC 28 01 00 00 48 8B 05 B6 A8 6C 01 48 33 C4 48 89 45 10",true},
}};
inline constexpr std::array<Witness,49> witnesses={{
    {0x2cfeac,"4D 8B E9"},
    {0x2cfeb4,"44 0F 28 D2"},
    {0x2cfeb8,"44 8B E2"},
    {0x2cfebb,"4C 8B F9"},
    {0x2cff94,"8B 83 B8 FD FF FF"},
    {0x2cff9e,"41 F6 45 18 02"},
    {0x2cffa9,"41 F6 45 08 80"},
    {0x2cffbb,"41 F6 45 18 04"},
    {0x2cffcb,"41 F7 45 08 00 01 00 00"},
    {0x2cffee,"49 8B 8D 20 02 00 00"},
    {0x2cfff5,"48 0F AB C1"},
    {0x45527e,"41 B8 E8 BD 00 00"},
    {0x77688,"81 4B 04 00 44 00 00"},
    {0x7b397,"48 8B 54 06 10"},
    {0x7b451,"48 83 C6 20"},
    {0x7b3d6,"81 62 08 7F FF FF FF"},
    {0x7b3e6,"09 42 08"},
    {0x7b41d,"81 62 08 FF FE FF FF"},
    {0x7b42d,"09 42 08"},
    {0x7adb4,"44 89 3E"},
    {0x7adb7,"89 7E 04"},
    {0x7add2,"48 89 46 10"},
    {0x7b2fc,"39 0D EE 9D A8 02"},
    {0x7b310,"48 8B 05 D1 9D A8 02"},
    {0x7b32f,"8B 0D 53 F7 AF 01"},
    {0x7b33c,"8B 0D 56 F7 AF 01"},
    {0x7b390,"48 8B 05 51 9D A8 02"},
    {0x7afb8,"83 B8 38 02 00 00 00"},
    {0x7afc5,"C6 46 1C 00"},
    {0x7afc9,"C6 46 1E 00"},
    {0x7b080,"45 85 FF"},
    {0x7b089,"44 88 7E 1C"},
    {0x7afb1,"48 8B 05 20 0E DC 02"},
    {0x4aa761,"48 8B 0D 70 16 99 02"},
    {0x4aa768,"4C 8B FA"},
    {0x4aa772,"44 88 44 24 40"},
    {0x4aa791,"45 84 C0"},
    {0x455252,"41 39 B6 5C BE 00 00"},
    {0x455273,"49 8D 56 70"},
    {0x455277,"48 81 C1 B0 00 00 00"},
    {0x45527e,"41 B8 E8 BD 00 00"},
    {0x455500,"41 B0 01"},
    {0x455503,"49 8B D1"},
    {0x4554e7,"41 8B 81 E4 BD 00 00 41 89 41 08"},
    {0x4aa98a,"0F B6 44 24 40 49 8B CE 88 44 24 30"},
    {0x4aaa1a,"48 81 C4 28 01 00 00 41 5F 41 5E 5E 5D C3"},
    {0x45526c,"48 8B 0D 6D 57 79 01"},
    {0x455284,"E8 28 1D 1B 01"},
    {0x455506,"E8 35 52 05 00"},
}};
inline constexpr std::array<Relative,9> relatives={{
    {0x7b2fc,6,2,0x2b050f0},
    {0x7b310,7,3,0x2b050e8},
    {0x7b32f,6,2,0x1b7aa88},
    {0x7b33c,6,2,0x1b7aa98},
    {0x7b390,7,3,0x2b050e8},
    {0x7afb1,7,3,0x2e3bdd8},
    {0x45526c,7,3,0x1bea9e0},
    {0x455284,5,1,0x1606fb1},
    {0x455506,5,1,0x4aa740},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t first_person_visibility_prepare=0x2cfe50;
inline constexpr uint32_t first_person_visibility_scheduler=0x7b2e0;
inline constexpr uint32_t first_person_visibility_bridge_branch=0x7afb1;
inline constexpr uint32_t first_person_visibility_submit=0x4aa740;
}
namespace flare_guard {
inline constexpr std::array<Entry,2> entries={{
    {"flare_project",0x446f70,"48 89 5C 24 08 48 89 54 24 10 57 48 81 EC E0 00 00 00 49 63 80 20 02 00 00",true},
    {"flare_draw",0x447ea0,"48 8B C4 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 58 FE FF FF 48 81 EC 70 02 00 00 48 C7 45 E0",true},
}};
inline constexpr std::array<Witness,12> witnesses={{
    {0x446f82,"49 63 80 20 02 00 00"},
    {0x446fa3,"F3 0F 10 84 CB 8C 00 00 00"},
    {0x446fb4,"F3 0F 10 84 CB B4 00 00 00"},
    {0x4470fa,"F3 41 0F 5E D0"},
    {0x447169,"F3 45 0F 5E C8"},
    {0x447316,"44 0F 28 64 24 70 4C 8D 9C 24 E0 00 00 00 49 8B 5B 10 45 0F 28 53 B0 49 8B E3 5F C3"},
    {0x447120,"4C 8D 43 70"},
    {0x447145,"48 63 87 20 02 00 00 0F 5B C9 48 8D 0C 80 48 C1 E1 04 F3 44 0F 58 CF 4C 03 C1"},
    {0x451096,"E8 D5 5E FF FF"},
    {0x44701d,"E8 BE 4B EA FF"},
    {0x447185,"E8 16 0D 00 00"},
    {0x4472e6,"E8 B5 0B 00 00"},
}};
inline constexpr std::array<Relative,4> relatives={{
    {0x451096,5,1,0x446f70},
    {0x44701d,5,1,0x2ebbe0},
    {0x447185,5,1,0x447ea0},
    {0x4472e6,5,1,0x447ea0},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t flare_project=0x446f70;
inline constexpr uint32_t flare_draw=0x447ea0;
}
namespace gameplay_bridge {
inline constexpr std::array<Entry,1> entries={{
    {"gameplay_saber_camera_producer",0x7b480,"48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 81 EC C0 00 00 00 80 3D DF 03 DC 02 00 49 8B F1 49 8B E8",true},
}};
inline constexpr std::array<Witness,8> witnesses={{
    {0x7b5cc,"48 83 B8 30 01 00 00 00 0F 85 E8 01 00 00"},
    {0x7b4e9,"80 3D 36 03 DC 02 00 0F 29 B4 24 B0 00 00 00 C6 05 9B 78 E2 02 00 0F 84 C0 00 00 00"},
    {0x7b5da,"F3 0F 10 25 3E 9B A8 02"},
    {0x7b5ef,"F3 0F 10 15 41 02 DC 02"},
    {0x7b696,"F3 0F 58 35 7A 9A A8 02"},
    {0x7b6a3,"F3 0F 58 2D 71 9A A8 02"},
    {0x7b4e9,"80 3D 36 03 DC 02 00"},
    {0x7b5c5,"48 8B 05 4C 0E DC 02"},
}};
inline constexpr std::array<Relative,6> relatives={{
    {0x7b5da,8,4,0x2b05120},
    {0x7b5ef,8,4,0x2e3b838},
    {0x7b696,8,4,0x2b05118},
    {0x7b6a3,8,4,0x2b0511c},
    {0x7b4e9,7,2,0x2e3b826},
    {0x7b5c5,7,3,0x2e3c418},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t gameplay_saber_camera_producer=0x7b480;
}
namespace hud {
inline constexpr std::array<Entry,1> entries={{
    {"hud_crosshair_draw",0xb3ffa0,"48 8B C4 48 89 58 10 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 A8 FE FF FF 48 81 EC 20 02 00 00 0F 29 70 B8 0F 29 78 A8 44 0F 29 40 98 44 0F 29 48 88 44 0F 29 90 78 FF FF FF 44 0F 29 98 68 FF FF FF 48 8B 05 27 50 03 01",true},
}};
inline constexpr std::array<Witness,3> witnesses={{
    {0xb40007,"44 84 B2 E0 01 00 00"},
    {0xb3eee9,"E8 B2 10 00 00"},
    {0xb3ef55,"E8 46 10 00 00"},
}};
inline constexpr std::array<Relative,2> relatives={{
    {0xb3eee9,5,1,0xb3ffa0},
    {0xb3ef55,5,1,0xb3ffa0},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t hud_crosshair_draw=0xb3ffa0;
}
namespace hud_layout {
inline constexpr std::array<Entry,1> entries={{
    {"hud_gameplay_draw",0xb12b08,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 57 41 55 41 56 48 83 EC 30 48 0F BF 3D 90 C7 E9 01 83 CE FF",true},
}};
inline constexpr std::array<Witness,8> witnesses={{
    {0xb12b3a,"8B B4 B8 B8 00 00 00"},
    {0xb12b65,"83 FE FF 0F 84 11 03 00 00 84 C9 0F 84 09 03 00 00"},
    {0xb32106,"E8 FD 09 FE FF"},
    {0xb12b20,"48 0F BF 3D 90 C7 E9 01"},
    {0xb12b33,"48 8B 05 56 02 39 02"},
    {0xb12dc4,"E8 5B BF 02 00"},
    {0xb12df0,"E8 47 DB 13 00"},
    {0xb12dfc,"E8 2F 1A 06 00"},
}};
inline constexpr std::array<Relative,6> relatives={{
    {0xb32106,5,1,0xb12b08},
    {0xb12b20,8,4,0x29af2b8},
    {0xb12b33,7,3,0x2ea2d90},
    {0xb12dc4,5,1,0xb3ed24},
    {0xb12df0,5,1,0xc5093c},
    {0xb12dfc,5,1,0xb74830},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t hud_gameplay_draw=0xb12b08;
}
namespace hud_target {
inline constexpr std::array<Entry,9> entries={{
    {"hud_target_bind",0x205e40,"40 53 56 57 41 56 41 57 48 83 EC 40 0F 10 02 4C 8B FA 45 33 C0 48 8B D9 0F 11 41 18 0F 10 4A 10",true},
    {"hud_target_surface_select",0xad5f0,"4C 8B 91 A8 00 00 00 4C 8B C1 4D 85 D2 74 45 48 8B 05 B2 D0 B3 01 44 8B 88 D0 01 00 00 41 8B C1",false},
    {"hud_target_viewport",0x206160,"40 53 48 83 EC 50 48 8B 05 A3 EE 96 01 48 33 C4 48 89 44 24 48 41 8D 04 11 66 0F 6E C2 0F 5B C0",true},
    {"hud_target_rtv_accessor",0x22b7b0,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 41 8B F9 41 8B F0 0F B6 DA 4C 8B D9 E8 20 1E E8 FF",true},
    {"hud_target_dsv_accessor",0x22b830,"48 83 EC 28 44 0F B6 DA E8 B3 1D E8 FF 45 84 DB 74 0C 48 8B 80 10 01 00 00 48 83 C4 28 C3 48 8B",true},
    {"hud_target_dimensions",0x1dc120,"F3 0F 10 0D D0 4D 62 01 4C 8B C9 89 51 50 0F 28 D1 44 89 41 54 85 D2 7E 0B 66 0F 6E C2 0F 5B C0",false},
    {"hud_target_conflicts",0x2059b0,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 20 45 33 FF 48 8D 99 28 10",true},
    {"hud_target_alias_check",0x22b700,"40 53 48 83 EC 20 4C 8B DA 48 8B D9 E8 DF 1E E8 FF 4C 8B C0 4C 3B 98 18 01 00 00 0F 84 7E 00 00",true},
    {"hud_target_release",0x22b0a0,"48 89 5C 24 18 55 48 83 EC 20 33 ED 48 89 74 24 30 48 8B D9 48 89 7C 24 38 8B F5 39 A9 F0 00 00",true},
}};
inline constexpr std::array<Witness,14> witnesses={{
    {0x205e58,"0F 11 41 18"},
    {0x205e7b,"F2 0F 11 41 58"},
    {0x20611c,"48 8B 8B E0 0C 00 00"},
    {0x206123,"4C 8D 83 00 0D 00 00"},
    {0x20612a,"4C 8B 8B 20 0D 00 00"},
    {0x206131,"8B 93 F8 0C 00 00"},
    {0x20613a,"FF 90 08 01 00 00"},
    {0x206148,"B0 01"},
    {0x205e80,"E8 9B 62 FD FF"},
    {0x205f25,"E8 C6 76 EA FF"},
    {0x205fc9,"E8 E2 F9 FF FF"},
    {0x2060e3,"E8 38 60 FD FF"},
    {0x203643,"48 8D 05 C6 66 5F 01"},
    {0x1efa3d,"48 89 05 9C C3 C4 02"},
}};
inline constexpr std::array<Relative,6> relatives={{
    {0x205e80,5,1,0x1dc120},
    {0x205f25,5,1,0xad5f0},
    {0x205fc9,5,1,0x2059b0},
    {0x2060e3,5,1,0x1dc120},
    {0x203643,7,3,0x17f9d10},
    {0x1efa3d,7,3,0x2e3bde0},
}};
inline constexpr std::array<Pointer,6> pointers={{
    {0x17f9e08,0x205e40},
    {0x17f9e30,0x206160},
    {0x17fb6e0,0x22b7b0},
    {0x17fb6e8,0x22b830},
    {0x17fb620,0x1f4b80},
    {0x17fb628,0x1f4bc0},
}};
inline constexpr uint32_t hud_target_bind=0x205e40;
inline constexpr uint32_t hud_target_surface_select=0xad5f0;
inline constexpr uint32_t hud_target_viewport=0x206160;
inline constexpr uint32_t hud_target_rtv_accessor=0x22b7b0;
inline constexpr uint32_t hud_target_dsv_accessor=0x22b830;
inline constexpr uint32_t hud_target_dimensions=0x1dc120;
inline constexpr uint32_t hud_target_conflicts=0x2059b0;
inline constexpr uint32_t hud_target_alias_check=0x22b700;
inline constexpr uint32_t hud_target_release=0x22b0a0;
}
namespace muzzle {
inline constexpr std::array<Entry,6> entries={{
    {"muzzle_fire",0xb7a374,"48 89 5C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 C0 E1 FF FF B8 40 1F 00 00 E8 CA CA A8 00 48 2B E0 0F 29 B4 24 30 1F 00 00 0F 29 BC 24 20 1F 00 00 44 0F 29 84 24 10 1F 00 00 44 0F",true},
    {"muzzle_markers",0xb3701c,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 50 4C 8B 35 BD 5D 26 02 45 33 FF 44 0F B7 D1 49 83 C6 34 41 0F B7 D9 8B E9 49 8B F8 48 8B F2 4F 8D 1C 52 4C 8B 15 EB B1 10",true},
    {"muzzle_query",0xb67fa8,"48 8B C4 48 89 58 10 55 56 57 41 54 41 55 41 56 41 57 48 8D 68 A8 48 81 EC 20 01 00 00 0F 29 70 B8 0F 29 78 A8 44 0F 29 40 98 44 0F 29 48 88 44 0F 29 90 78 FF FF FF 48 8B 05 2A D0 00 01 48 33",true},
    {"muzzle_direct_query",0xb68284,"48 89 5C 24 10 55 56 57 41 56 41 57 48 81 EC A0 00 00 00 48 8B 05 72 CD 00 01 48 33 C4 48 89 84 24 98 00 00 00 48 63 F9 49 8B D8 0F B7 CF 0F B7 F2 E8 EA CB FA FF 83 23 00 41 83 CF FF 44 89 7B",true},
    {"muzzle_target_validate",0xb698d0,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 8B 79 0C 48 8B F2 83 CA FF 8B CF 33 DB E8 B3 F0 FC FF 48 85 C0 74 04 89 3E B3 01 48 8B 74 24 38 8A C3 48 8B 5C 24 30 48 83 C4 20 5F C3 48 8B C4 48",true},
    {"muzzle_marker_owner",0xb777b0,"44 8B C1 41 BA 10 00 00 00 0F B7 C9 48 8D 14 49 48 8B 0D 81 AA 0C 01 48 63 41 34 48 03 C8 4C 63 4C 91 08 48 8B 15 1E 56 22 02 49 8B C9 48 8D 42 44 49 03 C1 41 83 F9 FF 49 0F 44 C2 F6 00 01 74",false},
}};
inline constexpr std::array<Witness,9> witnesses={{
    {0xb7a56f,"E8 A8 CA FB FF"},
    {0xb7a791,"E8 EA 60 F8 FF"},
    {0xb7a853,"E8 E8 5E F8 FF"},
    {0xb7a8b0,"E8 4B D2 FE FF"},
    {0xb67bdf,"E8 30 D3 FA FF"},
    {0xb680f8,"E8 EF 02 00 00"},
    {0xb6839b,"E8 4C 00 00 00"},
    {0xa98617,"E8 8C F9 0C 00"},
    {0xa98923,"E8 5C F9 0C 00"},
}};
inline constexpr std::array<Relative,9> relatives={{
    {0xb7a56f,5,1,0xb3701c},
    {0xb7a791,5,1,0xb00880},
    {0xb7a853,5,1,0xb00740},
    {0xb7a8b0,5,1,0xb67b00},
    {0xb67bdf,5,1,0xb14f14},
    {0xb680f8,5,1,0xb683ec},
    {0xb6839b,5,1,0xb683ec},
    {0xa98617,5,1,0xb67fa8},
    {0xa98923,5,1,0xb68284},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t muzzle_fire=0xb7a374;
inline constexpr uint32_t muzzle_markers=0xb3701c;
inline constexpr uint32_t muzzle_query=0xb67fa8;
inline constexpr uint32_t muzzle_direct_query=0xb68284;
inline constexpr uint32_t muzzle_target_validate=0xb698d0;
inline constexpr uint32_t muzzle_marker_owner=0xb777b0;
}
namespace network_input {
inline constexpr std::array<Entry,3> entries={{
    {"action_build",0xa9a8a4,"48 8B 41 08 4C 8B C1 48 89 42 04 8B 01 89 02 8A 41 1C 88 42 18 8A 41 1D 88 42 19 0F B7 41 1E 66",false},
    {"connection_read",0xaaf857,"0F BF 05 82 3E 07 02 85 C0 74 0D 83 F8 01 74 28 83 C0 FE 83 F8 01 77 0A",false},
    {"seat_direction_transform",0xb0584c,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 55 48 8D 68 A1 48 81 EC 00 01 00 00 4C 8B 1D 8A 75",true},
}};
inline constexpr std::array<Witness,5> witnesses={{
    {0xa9a8cf,"48 8B 41 10 48 89 42 0C 8B 41 18 89 42 14 0F B7 41 04 66 89 42 1E"},
    {0xa9988d,"8B CB E8 6C 12 00 00 0F 10 07"},
    {0xa99888,"E8 ?? ?? ?? ??"},
    {0xa99877,"48 8B 05 F2 65 2F 02"},
    {0xaaf857,"0F BF 05 82 3E 07 02"},
}};
inline constexpr std::array<Relative,3> relatives={{
    {0xa99888,5,1,0xa9a8a4},
    {0xa99877,7,3,0x2d8fe70},
    {0xaaf857,7,3,0x2b236e0},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t action_build=0xa9a8a4;
inline constexpr uint32_t connection_read=0xaaf857;
inline constexpr uint32_t seat_direction_transform=0xb0584c;
inline constexpr uint32_t control_pointer=0x2d8fe70;
inline constexpr uint32_t connection_type=0x2b236e0;
}
namespace player_state {
inline constexpr std::array<Entry,13> entries={{
    {"state_datum_get",0xbbb8d0,"45 33 C0 4C 8B D1 83 FA FF 74 3D 44 8B CA 41 C1 F9 10 66 85 D2 78 31 66 3B 51 20 7D 2B 0F B7 49 22 0F BF C2 0F AF C1 49 63 4A 34 48 98 49 03 C2 48 03 C8 66 44 39 01 74 0F 66 45 85 C9 74 06 66 44 39 09 75 03 4C 8B C1 49 8B C0 C3",false},
    {"state_output_player",0xa999e8,"41 83 C9 FF 4C 8B D2 41 3B C9 74 12 48 8B 05 95 93 40 02 4C 63 C1 46 8B 8C 80 B8 00 00 00",false},
    {"state_player_unit",0xad0304,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48 8B 05 66 01 17 01 49 8B F0 F3 0F 10 42",true},
    {"state_control_user_loop",0xa997b8,"48 8B C4 48 89 58 08 48 89 68 18 48 89 70 20 57 41 54 41 56 48 81 EC 10 01 00 00 0F 29 70 D8 48",true},
    {"state_control_admission",0xa9915c,"48 8B C4 48 89 58 20 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 88 F7 FF FF 48 81 EC 40 09 00 00 0F 29 70 B8 48 8B 05 89 BE 0D 01 48 33 C4 48 89 85 20 08 00",true},
    {"state_control_output_copy",0xa9ab00,"48 8B 15 69 53 2F 02 48 63 C1 4C 6B C0 58 41 83 7C 10 10 FF 74 46 48 8D 8A 70 01 00 00 41 B9 04 00 00 00",false},
    {"state_user_perspective",0xb14ea4,"48 0F BF C1 4C 8D 05 B1 6A 28 02 48 69 C8 F8 00 00 00 48 8D 15 7F D7 13 00 4A 8B 44 01 10 48 3B C2",false},
    {"state_fp_visibility",0xb275b8,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 55 41 54 41 55 41 56 41 57 48 8D A8 E8 F2 FF FF 48 81 EC F0 0D 00 00 0F",true},
    {"state_object_try_get",0xb389a4,"40 53 48 83 EC 20 8B DA 8B D1 48 8B 0D 93 98 10 01 E8 16 2F 08 00 4C 8B D8 33 C0 4D 85 DB 74 28 41 0F B6 4B",true},
    {"state_weapon_owner",0xb77814,"48 89 5C 24 08 57 48 83 EC 20 0F B7 C9 83 CB FF 48 8D 14 49 48 8B 0D 19 AA 0C 01",true},
    {"state_equipped_record",0xb27510,"40 53 48 83 EC 20 B9 11 00 00 00 E8 88 AB FF FF 0F B7 0D 91 7D E8 01 84 C0 0F 94 C0 41 83 C9 FF 66 41 3B C9 74 79 84 C0 74 75 48 0F BF C1 48 69",true},
    {"state_unit_player_backlink",0xb7a374,"48 89 5C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 C0 E1 FF FF B8 40 1F 00 00",true},
    {"state_unit_parent",0xb04d00,"48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC A0 00 00 00 4C 8B 0D 26 D5 13 01 33 DB 48 8B 2D CD 80 29 02",true},
}};
inline constexpr std::array<Witness,62> witnesses={{
    {0xbbb8e2,"66 85 D2 78 31 66 3B 51 20 7D 2B 0F B7 49 22"},
    {0xbbb8f1,"0F BF C2 0F AF C1 49 63 4A 34 48 98 49 03 C2 48 03 C8 66 44 39 01 74 0F 66 45 85 C9 74 06 66 44 39 09 75 03 4C 8B C1 49 8B C0 C3"},
    {0xa999fb,"4C 63 C1 46 8B 8C 80 B8 00 00 00"},
    {0xa99a0d,"48 0F BF C1 48 81 C2 7C 01 00 00 4C 6B C0 38 41 8B C9 49 03 D0"},
    {0xa999f4,"48 8B 05 95 93 40 02"},
    {0xa99a06,"48 8B 15 63 64 2F 02"},
    {0xa99a25,"E9 DA 68 03 00"},
    {0xad0325,"0F B7 C9 4C 69 C9 20 0C 00 00"},
    {0xad037b,"74 10 8B 4F 64 83 F9 FF 74 08 48 8B D6 E8 BF 54 03 00"},
    {0xad0313,"48 8B 05 66 01 17 01"},
    {0xa9983c,"4C 63 F3 43 8B 4C B0 04 83 F9 FF"},
    {0xa99863,"49 6B CE 58"},
    {0xa99835,"4C 8B 05 54 95 40 02"},
    {0xa9985e,"E8 F9 F8 FF FF"},
    {0xa99877,"48 8B 05 F2 65 2F 02"},
    {0xa9988f,"E8 6C 12 00 00"},
    {0xa991f4,"48 0F BF C3 48 8D 0D 01 6E 56 FF 48 69 C0 F8 00 00 00 48 89 44 24 58 44 38 BC 08 B9 B9 D9 02"},
    {0xa99215,"44 39 3D AC BD 19 01 75 09 83 3D 3B C5 0E 01 FF 75 09 0F B7 9D 1C 08 00 00 EB 20"},
    {0xa994c7,"44 38 78 02 0F 85 48 01 00 00"},
    {0xa994e7,"44 38 78 0A 0F 85 28 01 00 00"},
    {0xa9963e,"46 38 BC 00 B8 B9 D9 02 75 18"},
    {0xa992df,"46 8B 5C 36 10 41 83 C8 FF 45 3B D8 0F 84 06 04 00 00"},
    {0xa9919b,"4C 8B 35 CE 6C 2F 02"},
    {0xa99215,"44 39 3D AC BD 19 01"},
    {0xa9921e,"83 3D 3B C5 0E 01 FF"},
    {0xa994c0,"48 8B 05 A1 68 40 02"},
    {0xa994e0,"48 8B 05 21 6D 40 02"},
    {0xa9965b,"E8 BC 05 00 00"},
    {0xa9ab07,"48 63 C1 4C 6B C0 58 41 83 7C 10 10 FF 74 46 48"},
    {0xa9ab23,"41 8B 44 10 10 39 01 75 26 41 0F 10 44 10 14"},
    {0xa9ab00,"48 8B 15 69 53 2F 02"},
    {0xb14eaf,"48 69 C8 F8 00 00 00"},
    {0xb14edd,"42 0F B7 44 01 5C C3"},
    {0xb14f0d,"66 42 89 44 01 5C C3"},
    {0xb14ea8,"4C 8D 05 B1 6A 28 02"},
    {0xb14eb6,"48 8D 15 7F D7 13 00"},
    {0xb14ee4,"48 8D 15 B9 DD 13 00"},
    {0xb14ef7,"48 8D 15 26 F2 0C 00"},
    {0xb27626,"48 69 D8 94 1E 00 00"},
    {0xb2765c,"44 8A 03 41 8D 44 24 01 44 84 C0"},
    {0xb27631,"48 03 1D 58 57 27 02"},
    {0xb389c4,"41 0F B6 4B 03 0F A3 CB 73 1E 4C 8B 05 23 44 26 02 49 63 53 08 49 83 C0 34 4C 03 C2 41 83 7B 08 FF 4C 0F 44 C0"},
    {0xb389ae,"48 8B 0D 93 98 10 01"},
    {0xb389b5,"E8 16 2F 08 00"},
    {0xb389ce,"4C 8B 05 23 44 26 02"},
    {0xb77847,"48 81 C2 0C 01 00 00"},
    {0xb77858,"8B 3A 3B FB 74 10 8D 53 04 8B CF E8 3C 11 FC FF 48 85 C0 0F 45 DF"},
    {0xb77828,"48 8B 0D 19 AA 0C 01"},
    {0xb77840,"48 8B 15 B1 55 22 02"},
    {0xb77863,"E8 3C 11 FC FF"},
    {0xb2753e,"48 69 D0 94 1E 00 00"},
    {0xb2754c,"44 39 4A 04 74 5D 44 39 4A 08"},
    {0xb27545,"48 03 15 44 58 27 02"},
    {0xb7a741,"F7 03 00 40 00 00"},
    {0xb7a64d,"44 8B B6 F8 01 00 00"},
    {0xb7a545,"E8 CA D2 FF FF"},
    {0xb7a608,"E8 97 E3 FB FF"},
    {0xb7a791,"E8 EA 60 F8 FF"},
    {0xb7a853,"E8 E8 5E F8 FF"},
    {0xb04d61,"8B 8E D8 00 00 00"},
    {0xb04d6a,"41 3B CF 0F 85 A4 00 00 00"},
    {0xb04d5c,"E8 E7 68 F9 FF"},
}};
inline constexpr std::array<Relative,32> relatives={{
    {0xa999f4,7,3,0x2ea2d90},
    {0xa99a06,7,3,0x2d8fe70},
    {0xa99a25,5,1,0xad0304},
    {0xad0313,7,3,0x1c40480},
    {0xa99835,7,3,0x2ea2d90},
    {0xa9985e,5,1,0xa9915c},
    {0xa99877,7,3,0x2d8fe70},
    {0xa9988f,5,1,0xa9ab00},
    {0xa9919b,7,3,0x2d8fe70},
    {0xa99215,7,3,0x1c34fc8},
    {0xa9921e,7,2,0x1b85760},
    {0xa994c0,7,3,0x2e9fd68},
    {0xa994e0,7,3,0x2ea0208},
    {0xa9965b,5,1,0xa99c1c},
    {0xa9ab00,7,3,0x2d8fe70},
    {0xb14ea8,7,3,0x2d9b960},
    {0xb14eb6,7,3,0xc5263c},
    {0xb14ee4,7,3,0xc52ca4},
    {0xb14ef7,7,3,0xbe4124},
    {0xb27631,7,3,0x2d9cd90},
    {0xb389ae,7,3,0x1c42248},
    {0xb389b5,5,1,0xbbb8d0},
    {0xb389ce,7,3,0x2d9cdf8},
    {0xb77828,7,3,0x1c42248},
    {0xb77840,7,3,0x2d9cdf8},
    {0xb77863,5,1,0xb389a4},
    {0xb27545,7,3,0x2d9cd90},
    {0xb7a545,5,1,0xb77814},
    {0xb7a608,5,1,0xb389a4},
    {0xb7a791,5,1,0xb00880},
    {0xb7a853,5,1,0xb00740},
    {0xb04d5c,5,1,0xa9b648},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t state_datum_get=0xbbb8d0;
inline constexpr uint32_t state_output_player=0xa999e8;
inline constexpr uint32_t state_player_unit=0xad0304;
inline constexpr uint32_t state_control_user_loop=0xa997b8;
inline constexpr uint32_t state_control_admission=0xa9915c;
inline constexpr uint32_t state_control_output_copy=0xa9ab00;
inline constexpr uint32_t state_user_perspective=0xb14ea4;
inline constexpr uint32_t state_fp_visibility=0xb275b8;
inline constexpr uint32_t state_object_try_get=0xb389a4;
inline constexpr uint32_t state_weapon_owner=0xb77814;
inline constexpr uint32_t state_equipped_record=0xb27510;
inline constexpr uint32_t state_unit_player_backlink=0xb7a374;
inline constexpr uint32_t state_unit_parent=0xb04d00;
}
namespace unit_control {
inline constexpr std::array<Entry,7> entries={{
    {"unit_control_set",0xafe098,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 33 F6 44 0F B7 C9 83 CF FF 41 8B D8 44 8A 05 76 D5 07 01",true},
    {"unit_control_player_update",0xad0720,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8D A8 D8 FB FF FF 48 81 EC 00 05 00 00 48 8B",true},
    {"movement_consumer",0xbb5d88,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8D A8 38 FC FF FF 48 81 EC A0 04 00 00",true},
    {"movement_producer_secondary",0xbb1efc,"48 8B C4 48 89 58 10 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 18 FE FF FF 48 81 EC B0 02 00 00 0F 29 70 B8",true},
    {"movement_producer",0xbb31f4,"48 8B C4 48 89 58 18 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 68 FA FF FF 48 81 EC 60 06 00 00 0F 29 70 B8",true},
    {"movement_consumer_return",0xbb40f4,"8B 85 2C 04 00 00 83 C9 FF 3B C1 74 0F C6 83 DF 04 00 00 3C",false},
    {"movement_consumer_return_secondary",0xbb2c3d,"8B 45 CC 83 CA FF 3B C2 74 0F C6 83 DF 04 00 00 3C 89 83 E0 04 00 00",false},
}};
inline constexpr std::array<Witness,29> witnesses={{
    {0xafe11a,"0F 10 02 41 0F 11 82 78 04 00 00 0F 10 4A 10 41 0F 11 8A 88 04 00 00 0F 10 42 20 41 0F 11 82 98 04 00 00 0F 10 4A 30 41 0F 11 8A A8 04 00 00 0F 10 42 40 41 0F 11 82 B8 04 00 00"},
    {0xafe155,"F2 0F 10 42 0C F2 41 0F 11 82 58 02 00 00 8B 42 14 41 89 82 60 02 00 00 8B 42 18 41 89 82 64 02 00 00 8A 42 01 41 88 82 68 02 00 00"},
    {0xafe1da,"F2 0F 10 42 34 F2 41 0F 11 82 34 02 00 00 8B 42 3C 41 89 82 3C 02 00 00 F2 0F 10 42 28 F2 41 0F 11 82 10 02 00 00 8B 42 30 41 89 82 18 02 00 00 F2 0F 10 42 1C F2 41 0F 11 82 04 02 00 00 8B 42 24 41 89 82 0C 02 00 00"},
    {0xad0cb3,"8B 44 24 60 48 8D 4F 20 F2 0F 10 44 24 58"},
    {0xad0cee,"F2 0F 11 44 24 64 F2 0F 11 44 24 4C"},
    {0xad0d49,"44 8B 44 24 24 48 8D 54 24 30 8B 4B 64"},
    {0xad0d5b,"4C 8B 7C 24 28"},
    {0xad0d56,"E8 ?? ?? ?? ??"},
    {0xbb5dfe,"0F B7 59 04"},
    {0xbb5e4a,"48 8B F9 66 44 89 A1 A0 00 00 00"},
    {0xbb5fa3,"F3 44 0F 10 59 3C F3 0F 10 49 40 45 0F 28 EB F3 0F 10 41 18 F3 44 0F 59 69 14 8B 41 44 F3 44 0F 59 59 18 89 81 C0 00 00 00 F3 0F 59 C1 F3 0F 59 49 14 F3 44 0F 5C E8 F3 44 0F 58 D9"},
    {0xbb5fe5,"F3 44 0F 11 A9 B8 00 00 00 F3 44 0F 11 5D BC F3 44 0F 11 99 BC 00 00 00"},
    {0xbb6112,"F2 0F 10 4F 20"},
    {0xbb612e,"8B 47 28"},
    {0xbb1fa5,"F2 41 0F 10 40 30 45 33 FF 41 8B 48 38"},
    {0xbb1fb9,"89 74 24 30 F7 80 7C 01 00 00 00 08 00 00 66 44 89 7C 24 34 F2 0F 11 44 24 44 89 4C 24 4C"},
    {0xbb2003,"48 81 C2 50 02 00 00 49 03 D0 45 3B C1 48 0F 44 D0 F2 0F 10 02 8B 42 08"},
    {0xbb202c,"F2 0F 11 44 24 50"},
    {0xbb2050,"89 44 24 58"},
    {0xbb2112,"44 21 7C 24 6C 44 21 7C 24 70 44 21 7C 24 74"},
    {0xbb2c33,"48 8D 4C 24 30"},
    {0xbb2c38,"E8 4B 31 00 00"},
    {0xbb32d0,"F2 0F 10 43 30 48 8B F8 8B 43 38 44 89 A5 90 03 00 00 66 44 89 BD 94 03 00 00 F2 0F 11 85 A4 03 00 00 89 85 AC 03 00 00"},
    {0xbb32f8,"F7 87 7C 01 00 00 00 08 00 00 74 0A F2 0F 11 85 B0 03 00 00 EB 25 49 8D 82 50 02 00 00 B9 1C 02 00 00 49 03 C1 44 3B CE 48 0F 44 C1 F2 0F 10 00 F2 0F 11 85 B0 03 00 00 8B 40 08"},
    {0xbb3372,"89 85 B8 03 00 00"},
    {0xbb3452,"44 21 BD CC 03 00 00 44 21 BD D0 03 00 00"},
    {0xbb346a,"44 21 BD D4 03 00 00"},
    {0xbb40e8,"48 8D 8D 90 03 00 00"},
    {0xbb40ef,"E8 94 1C 00 00"},
}};
inline constexpr std::array<Relative,3> relatives={{
    {0xad0d56,5,1,0xafe098},
    {0xbb2c38,5,1,0xbb5d88},
    {0xbb40ef,5,1,0xbb5d88},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t unit_control_set=0xafe098;
inline constexpr uint32_t unit_control_player_update=0xad0720;
inline constexpr uint32_t movement_consumer=0xbb5d88;
inline constexpr uint32_t movement_producer_secondary=0xbb1efc;
inline constexpr uint32_t movement_producer=0xbb31f4;
inline constexpr uint32_t movement_consumer_return=0xbb40f4;
inline constexpr uint32_t movement_consumer_return_secondary=0xbb2c3d;
}
namespace vehicle {
inline constexpr std::array<Entry,3> entries={{
    {"vehicle_native_control_update",0xafbe54,"48 8B C4 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 68 88 48 81 EC 38 01 00 00 4C 8B 25 80 0F 2A 02 33 DB 0F 29",true},
    {"vehicle_seat_camera_info",0xb04ee4,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 48 89 78 20 41 56 48 83 EC 20 0F B7 01 33 ED 48 8B 15 3F D3 13 01",true},
    {"vehicle_following_camera",0xc52ca4,"48 8B C4 48 89 58 10 48 89 70 18 55 57 41 56 48 8D 68 A1 48 81 EC A0 00 00 00 0F 29 70 D8 48 8B F2",true},
}};
inline constexpr std::array<Witness,15> witnesses={{
    {0xafc245,"B9 04 03 00 00 49 8D 84 24 38 03 00 00 49 03 C6 45 8D 42 4E 45 3B F3 41 8D 52 90 48 0F 44 C1 8B 08 41 3B CB 0F 84 4C 01 00 00"},
    {0xafc33d,"41 BA 04 02 00 00 8B 00 83 E0 3F 09 01 49 8D 81 38 02 00 00 48 03 C2 49 8D 8C 24 38 02 00 00 45 3B C3 49 0F 44 C2 49 03 CE 45 3B F3 49 0F 44 CA F2 0F 10 00 F2 0F 11 01 8B 40 08 89 41 08"},
    {0xafc37b,"49 8D 81 8C 02 00 00 48 03 C2 49 8D 8C 24 8C 02 00 00 45 3B C3 41 8D 52 54 48 0F 44 C2 49 03 CE 45 3B F3 48 0F 44 CA F2 0F 10 00 F2 0F 11 01 8B 40 08 89 41 08"},
    {0xafc3bb,"B9 08 03 00 00 49 8D 84 24 3C 03 00 00 49 03 C6 45 3B F3 48 0F 44 C1 8B 08 41 3B CB 0F 84 60 01 00 00 49 8D 84 24 F6 00"},
    {0xafc485,"B8 10 02 00 00 49 8D 92 44 02 00 00 49 03 D0 49 8D 8C 24 44 02 00 00 45 3B C3 48 0F 44 D0 49 03 CE 45 3B F3 48 0F 44 C8 F2 0F 10 02 F2 0F 11 01 8B 42 08 89 41 08 B8 34 02 00 00 F2 0F 10 02 49 8D 8C 24 68 02 00 00 49 03 CE 45 3B F3 48 0F 44 C8 F2 0F 11 01 8B 42 08 BA D8 01 00 00 89 41 08"},
    {0xafc228,"41 83 CB FF F7 07 00 00 80 00 41 BA 74 00 00 00 48"},
    {0xb04f40,"8B B7 D8 00 00 00 41 3B F6 0F 84 8C 00 00 00 8D 55 03 8B CE E8 4B 3A 03 00"},
    {0xb04f83,"48 0F BF 87 D0 02 00 00 48 69 C0 1C 01 00 00 89 33 48"},
    {0xb04fa8,"0F B7 87 D0 02 00 00 48 8B 3D 42 7E 29 02 66 89 43 04"},
    {0xb04f54,"E8 4B 3A 03 00"},
    {0xc52e94,"48 0F BF 06 F3 0F 10 35 D8 CF CF 00 48 6B C8 38 48 8B 05 C5 CF 13 02 48 8B 8C 01 7C 01 00 00 48 89 4D 67 F3 0F 10 45 6B F3 0F 58 02 F3 0F 10 7D 67 F3 0F 58 7F 10 0F 2F F0 77 0C F3 0F 10 35 01 C7 CF 00 F3 0F 5D F0"},
    {0xc52edb,"0F 28 C6 48 8D 73 24 E8 3C 41 9B 00 44 0F 28 C8 0F 28 C7 E8 30 41 9B 00 F3 41 0F 59 C1 F3 0F 11 06 0F 28 C7 E8 25 41 9B 00 F3 41 0F 59 C1 F3 0F 11 46 04 0F 28 C6 E8 13 41 9B 00 48 8B 4D DF 4C 8D 45 C7 44 0F 28 D0 0F 28 CE F3 44 0F 11 56 08"},
    {0xb14ee4,"48 8D 15 B9 DD 13 00 48 3B C2 75 07 B8 01 00 00 00 EB 16"},
    {0xc52ea4,"48 8B 05 ?? ?? ?? ??"},
    {0xb14ee4,"48 8D 15 ?? ?? ?? ??"},
}};
inline constexpr std::array<Relative,3> relatives={{
    {0xb04f54,5,1,0xb389a4},
    {0xc52ea4,7,3,0x2d8fe70},
    {0xb14ee4,7,3,0xc52ca4},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t vehicle_native_control_update=0xafbe54;
inline constexpr uint32_t vehicle_seat_camera_info=0xb04ee4;
inline constexpr uint32_t vehicle_following_camera=0xc52ca4;
}
namespace vehicle_view {
inline constexpr std::array<Entry,1> entries={{
    {"vehicle_orientation_basis",0xb45178,"48 8B C4 48 89 50 10 55 53 56 57 41 54 41 56 41 57 48 8D 6C 24 90 48 81 EC 70 01 00 00",true},
}};
inline constexpr std::array<Witness,2> witnesses={{
    {0xb45498,"4C 8D 46 3C 48 8D 56 30 48 8D 4D 98 E8 43 D0 05 00"},
    {0xb454a4,"E8 43 D0 05 00"},
}};
inline constexpr std::array<Relative,1> relatives={{
    {0xb454a4,5,1,0xba24ec},
}};
inline constexpr std::array<Pointer,0> pointers={{
}};
inline constexpr uint32_t vehicle_orientation_basis=0xb45178;
}
}
